/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { Answer } from '../models';
import { CreateAnswerDto } from '../models';
import { UpdateAnswerDto } from '../models';
/**
 * AnswerApi - axios parameter creator
 * @export
 */
export declare const AnswerApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateAnswerDto} body
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerAddAnswer: (body: CreateAnswerDto, questionId: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerRemove: (id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {UpdateAnswerDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerUpdate: (body: UpdateAnswerDto, id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AnswerApi - functional programming interface
 * @export
 */
export declare const AnswerApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateAnswerDto} body
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerAddAnswer(body: CreateAnswerDto, questionId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Answer>>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerRemove(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Answer>>>;
    /**
     *
     * @param {UpdateAnswerDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerUpdate(body: UpdateAnswerDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Answer>>>;
};
/**
 * AnswerApi - factory interface
 * @export
 */
export declare const AnswerApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {CreateAnswerDto} body
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerAddAnswer(body: CreateAnswerDto, questionId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Answer>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerRemove(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Answer>>;
    /**
     *
     * @param {UpdateAnswerDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    answerControllerUpdate(body: UpdateAnswerDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Answer>>;
};
/**
 * AnswerApi - object-oriented interface
 * @export
 * @class AnswerApi
 * @extends {BaseAPI}
 */
export declare class AnswerApi extends BaseAPI {
    /**
     *
     * @param {CreateAnswerDto} body
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnswerApi
     */
    answerControllerAddAnswer(body: CreateAnswerDto, questionId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Answer>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnswerApi
     */
    answerControllerRemove(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Answer>>;
    /**
     *
     * @param {UpdateAnswerDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AnswerApi
     */
    answerControllerUpdate(body: UpdateAnswerDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Answer>>;
}
