/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { ChangePasswordDto } from '../models';
import { ChangePasswordResponseDto } from '../models';
import { ForgotPasswordDto } from '../models';
import { LoginDto } from '../models';
import { LoginResponseDto } from '../models';
import { RegisterDto } from '../models';
import { RegisterResponseDto } from '../models';
import { ResetPasswordDto } from '../models';
/**
 * AuthApi - axios parameter creator
 * @export
 */
export declare const AuthApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary პაროლის შეცვლა (ავტორიზებული მომხმარებლისთვის)
     * @param {ChangePasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerChangePassword: (body: ChangePasswordDto, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Facebook-ით ავტორიზაცია/რეგისტრაცია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerFacebookLogin: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary პაროლის აღდგენის მოთხოვნა (email-ის გაგზავნა)
     * @param {ForgotPasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerForgotPassword: (body: ForgotPasswordDto, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary მხოლოდ ადმინისტრატორის პანელი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetAdminDashboard: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary მიმდინარე მომხმარებლის პროფილი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary Google-ით ავტორიზაცია/რეგისტრაცია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGoogleLogin: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary მომხმარებლის ავტორიზაცია
     * @param {LoginDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin: (body: LoginDto, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary მომხმარებლის რეგისტრაცია
     * @param {RegisterDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister: (body: RegisterDto, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary პაროლის აღდგენა token-ით
     * @param {ResetPasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerResetPassword: (body: ResetPasswordDto, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * AuthApi - functional programming interface
 * @export
 */
export declare const AuthApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary პაროლის შეცვლა (ავტორიზებული მომხმარებლისთვის)
     * @param {ChangePasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerChangePassword(body: ChangePasswordDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<ChangePasswordResponseDto>>>;
    /**
     *
     * @summary Facebook-ით ავტორიზაცია/რეგისტრაცია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerFacebookLogin(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginResponseDto>>>;
    /**
     *
     * @summary პაროლის აღდგენის მოთხოვნა (email-ის გაგზავნა)
     * @param {ForgotPasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerForgotPassword(body: ForgotPasswordDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
    /**
     *
     * @summary მხოლოდ ადმინისტრატორის პანელი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetAdminDashboard(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
    /**
     *
     * @summary მიმდინარე მომხმარებლის პროფილი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
    /**
     *
     * @summary Google-ით ავტორიზაცია/რეგისტრაცია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGoogleLogin(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginResponseDto>>>;
    /**
     *
     * @summary მომხმარებლის ავტორიზაცია
     * @param {LoginDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin(body: LoginDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginResponseDto>>>;
    /**
     *
     * @summary მომხმარებლის რეგისტრაცია
     * @param {RegisterDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister(body: RegisterDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<RegisterResponseDto>>>;
    /**
     *
     * @summary პაროლის აღდგენა token-ით
     * @param {ResetPasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerResetPassword(body: ResetPasswordDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
};
/**
 * AuthApi - factory interface
 * @export
 */
export declare const AuthApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary პაროლის შეცვლა (ავტორიზებული მომხმარებლისთვის)
     * @param {ChangePasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerChangePassword(body: ChangePasswordDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ChangePasswordResponseDto>>;
    /**
     *
     * @summary Facebook-ით ავტორიზაცია/რეგისტრაცია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerFacebookLogin(options?: AxiosRequestConfig): Promise<AxiosResponse<LoginResponseDto>>;
    /**
     *
     * @summary პაროლის აღდგენის მოთხოვნა (email-ის გაგზავნა)
     * @param {ForgotPasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerForgotPassword(body: ForgotPasswordDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary მხოლოდ ადმინისტრატორის პანელი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetAdminDashboard(options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary მიმდინარე მომხმარებლის პროფილი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGetProfile(options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary Google-ით ავტორიზაცია/რეგისტრაცია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerGoogleLogin(options?: AxiosRequestConfig): Promise<AxiosResponse<LoginResponseDto>>;
    /**
     *
     * @summary მომხმარებლის ავტორიზაცია
     * @param {LoginDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerLogin(body: LoginDto, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginResponseDto>>;
    /**
     *
     * @summary მომხმარებლის რეგისტრაცია
     * @param {RegisterDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerRegister(body: RegisterDto, options?: AxiosRequestConfig): Promise<AxiosResponse<RegisterResponseDto>>;
    /**
     *
     * @summary პაროლის აღდგენა token-ით
     * @param {ResetPasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    authControllerResetPassword(body: ResetPasswordDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
};
/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export declare class AuthApi extends BaseAPI {
    /**
     *
     * @summary პაროლის შეცვლა (ავტორიზებული მომხმარებლისთვის)
     * @param {ChangePasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerChangePassword(body: ChangePasswordDto, options?: AxiosRequestConfig): Promise<AxiosResponse<ChangePasswordResponseDto>>;
    /**
     *
     * @summary Facebook-ით ავტორიზაცია/რეგისტრაცია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerFacebookLogin(options?: AxiosRequestConfig): Promise<AxiosResponse<LoginResponseDto>>;
    /**
     *
     * @summary პაროლის აღდგენის მოთხოვნა (email-ის გაგზავნა)
     * @param {ForgotPasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerForgotPassword(body: ForgotPasswordDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary მხოლოდ ადმინისტრატორის პანელი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerGetAdminDashboard(options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary მიმდინარე მომხმარებლის პროფილი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerGetProfile(options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary Google-ით ავტორიზაცია/რეგისტრაცია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerGoogleLogin(options?: AxiosRequestConfig): Promise<AxiosResponse<LoginResponseDto>>;
    /**
     *
     * @summary მომხმარებლის ავტორიზაცია
     * @param {LoginDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerLogin(body: LoginDto, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginResponseDto>>;
    /**
     *
     * @summary მომხმარებლის რეგისტრაცია
     * @param {RegisterDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerRegister(body: RegisterDto, options?: AxiosRequestConfig): Promise<AxiosResponse<RegisterResponseDto>>;
    /**
     *
     * @summary პაროლის აღდგენა token-ით
     * @param {ResetPasswordDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    authControllerResetPassword(body: ResetPasswordDto, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
}
