/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { CategoryResponseDto } from '../models';
import { CreateCategoryDto } from '../models';
import { UpdateCategoryDto } from '../models';
/**
 * CategoriesApi - axios parameter creator
 * @export
 */
export declare const CategoriesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary ახალი კატეგორიის შექმნა
     * @param {CreateCategoryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerCreate: (body: CreateCategoryDto, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary ყველა კატეგორიის მიღება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerFindAll: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary კონკრეტული კატეგორიის მიღება
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerFindOne: (id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary კატეგორიის წაშლა
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerRemove: (id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary კატეგორიის განახლება
     * @param {UpdateCategoryDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerUpdate: (body: UpdateCategoryDto, id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * CategoriesApi - functional programming interface
 * @export
 */
export declare const CategoriesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary ახალი კატეგორიის შექმნა
     * @param {CreateCategoryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerCreate(body: CreateCategoryDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CategoryResponseDto>>>;
    /**
     *
     * @summary ყველა კატეგორიის მიღება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerFindAll(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
    /**
     *
     * @summary კონკრეტული კატეგორიის მიღება
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
    /**
     *
     * @summary კატეგორიის წაშლა
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerRemove(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
    /**
     *
     * @summary კატეგორიის განახლება
     * @param {UpdateCategoryDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerUpdate(body: UpdateCategoryDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<CategoryResponseDto>>>;
};
/**
 * CategoriesApi - factory interface
 * @export
 */
export declare const CategoriesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary ახალი კატეგორიის შექმნა
     * @param {CreateCategoryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerCreate(body: CreateCategoryDto, options?: AxiosRequestConfig): Promise<AxiosResponse<CategoryResponseDto>>;
    /**
     *
     * @summary ყველა კატეგორიის მიღება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerFindAll(options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary კონკრეტული კატეგორიის მიღება
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary კატეგორიის წაშლა
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerRemove(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary კატეგორიის განახლება
     * @param {UpdateCategoryDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    categoryControllerUpdate(body: UpdateCategoryDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CategoryResponseDto>>;
};
/**
 * CategoriesApi - object-oriented interface
 * @export
 * @class CategoriesApi
 * @extends {BaseAPI}
 */
export declare class CategoriesApi extends BaseAPI {
    /**
     *
     * @summary ახალი კატეგორიის შექმნა
     * @param {CreateCategoryDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    categoryControllerCreate(body: CreateCategoryDto, options?: AxiosRequestConfig): Promise<AxiosResponse<CategoryResponseDto>>;
    /**
     *
     * @summary ყველა კატეგორიის მიღება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    categoryControllerFindAll(options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary კონკრეტული კატეგორიის მიღება
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    categoryControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary კატეგორიის წაშლა
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    categoryControllerRemove(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary კატეგორიის განახლება
     * @param {UpdateCategoryDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CategoriesApi
     */
    categoryControllerUpdate(body: UpdateCategoryDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<CategoryResponseDto>>;
}
