/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateColorDto } from '../models';
// @ts-ignore
import type { UpdateColorDto } from '../models';
/**
 * ColorsApi - axios parameter creator
 */
export const ColorsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ახალი ფერის შექმნა (ADMIN)
         * @param {CreateColorDto} createColorDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerCreate: async (createColorDto: CreateColorDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createColorDto' is not null or undefined
            assertParamExists('colorsControllerCreate', 'createColorDto', createColorDto)
            const localVarPath = `/colors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createColorDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ფერების სია
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/colors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კონკრეტული ფერის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('colorsControllerFindOne', 'id', id)
            const localVarPath = `/colors/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ფერის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('colorsControllerRemove', 'id', id)
            const localVarPath = `/colors/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ფერის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateColorDto} updateColorDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerUpdate: async (id: string, updateColorDto: UpdateColorDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('colorsControllerUpdate', 'id', id)
            // verify required parameter 'updateColorDto' is not null or undefined
            assertParamExists('colorsControllerUpdate', 'updateColorDto', updateColorDto)
            const localVarPath = `/colors/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateColorDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ColorsApi - functional programming interface
 */
export const ColorsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ColorsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary ახალი ფერის შექმნა (ADMIN)
         * @param {CreateColorDto} createColorDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async colorsControllerCreate(createColorDto: CreateColorDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.colorsControllerCreate(createColorDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorsApi.colorsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ფერების სია
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async colorsControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.colorsControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorsApi.colorsControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კონკრეტული ფერის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async colorsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.colorsControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorsApi.colorsControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ფერის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async colorsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.colorsControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorsApi.colorsControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ფერის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateColorDto} updateColorDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async colorsControllerUpdate(id: string, updateColorDto: UpdateColorDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.colorsControllerUpdate(id, updateColorDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ColorsApi.colorsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ColorsApi - factory interface
 */
export const ColorsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ColorsApiFp(configuration)
    return {
        /**
         * 
         * @summary ახალი ფერის შექმნა (ADMIN)
         * @param {CreateColorDto} createColorDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerCreate(createColorDto: CreateColorDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.colorsControllerCreate(createColorDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ფერების სია
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.colorsControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კონკრეტული ფერის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.colorsControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ფერის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.colorsControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ფერის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateColorDto} updateColorDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        colorsControllerUpdate(id: string, updateColorDto: UpdateColorDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.colorsControllerUpdate(id, updateColorDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ColorsApi - object-oriented interface
 */
export class ColorsApi extends BaseAPI {
    /**
     * 
     * @summary ახალი ფერის შექმნა (ADMIN)
     * @param {CreateColorDto} createColorDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public colorsControllerCreate(createColorDto: CreateColorDto, options?: RawAxiosRequestConfig) {
        return ColorsApiFp(this.configuration).colorsControllerCreate(createColorDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ფერების სია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public colorsControllerFindAll(options?: RawAxiosRequestConfig) {
        return ColorsApiFp(this.configuration).colorsControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კონკრეტული ფერის მიღება
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public colorsControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return ColorsApiFp(this.configuration).colorsControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ფერის წაშლა (ADMIN)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public colorsControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return ColorsApiFp(this.configuration).colorsControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ფერის განახლება (ADMIN)
     * @param {string} id 
     * @param {UpdateColorDto} updateColorDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public colorsControllerUpdate(id: string, updateColorDto: UpdateColorDto, options?: RawAxiosRequestConfig) {
        return ColorsApiFp(this.configuration).colorsControllerUpdate(id, updateColorDto, options).then((request) => request(this.axios, this.basePath));
    }
}

