/* tslint:disable */
/* eslint-disable */
/**
 * My First Nest API
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { Favorite } from '../models';
/**
 * FavoritesApi - axios parameter creator
 */
export const FavoritesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary კითხვის დამატება ფავორიტებში
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        favoriteControllerAddFavorite: async (questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('favoriteControllerAddFavorite', 'questionId', questionId)
            const localVarPath = `/favorites/{questionId}`
                .replace('{questionId}', encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ჩემი ფავორიტი კითხვები (pagination-ით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {FavoriteControllerFindMyFavoritesOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        favoriteControllerFindMyFavorites: async (page?: number, limit?: number, sortBy?: string, order?: FavoriteControllerFindMyFavoritesOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/favorites`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვის წაშლა ფავორიტებიდან
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        favoriteControllerRemoveFavorite: async (questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('favoriteControllerRemoveFavorite', 'questionId', questionId)
            const localVarPath = `/favorites/{questionId}`
                .replace('{questionId}', encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FavoritesApi - functional programming interface
 */
export const FavoritesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FavoritesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary კითხვის დამატება ფავორიტებში
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async favoriteControllerAddFavorite(questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.favoriteControllerAddFavorite(questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FavoritesApi.favoriteControllerAddFavorite']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ჩემი ფავორიტი კითხვები (pagination-ით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {FavoriteControllerFindMyFavoritesOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async favoriteControllerFindMyFavorites(page?: number, limit?: number, sortBy?: string, order?: FavoriteControllerFindMyFavoritesOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.favoriteControllerFindMyFavorites(page, limit, sortBy, order, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FavoritesApi.favoriteControllerFindMyFavorites']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვის წაშლა ფავორიტებიდან
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async favoriteControllerRemoveFavorite(questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Favorite>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.favoriteControllerRemoveFavorite(questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FavoritesApi.favoriteControllerRemoveFavorite']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FavoritesApi - factory interface
 */
export const FavoritesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FavoritesApiFp(configuration)
    return {
        /**
         * 
         * @summary კითხვის დამატება ფავორიტებში
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        favoriteControllerAddFavorite(questionId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.favoriteControllerAddFavorite(questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ჩემი ფავორიტი კითხვები (pagination-ით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {FavoriteControllerFindMyFavoritesOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        favoriteControllerFindMyFavorites(page?: number, limit?: number, sortBy?: string, order?: FavoriteControllerFindMyFavoritesOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.favoriteControllerFindMyFavorites(page, limit, sortBy, order, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვის წაშლა ფავორიტებიდან
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        favoriteControllerRemoveFavorite(questionId: string, options?: RawAxiosRequestConfig): AxiosPromise<Favorite> {
            return localVarFp.favoriteControllerRemoveFavorite(questionId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FavoritesApi - object-oriented interface
 */
export class FavoritesApi extends BaseAPI {
    /**
     * 
     * @summary კითხვის დამატება ფავორიტებში
     * @param {string} questionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public favoriteControllerAddFavorite(questionId: string, options?: RawAxiosRequestConfig) {
        return FavoritesApiFp(this.configuration).favoriteControllerAddFavorite(questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ჩემი ფავორიტი კითხვები (pagination-ით)
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {FavoriteControllerFindMyFavoritesOrderEnum} [order] დალაგების მიმართულება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public favoriteControllerFindMyFavorites(page?: number, limit?: number, sortBy?: string, order?: FavoriteControllerFindMyFavoritesOrderEnum, options?: RawAxiosRequestConfig) {
        return FavoritesApiFp(this.configuration).favoriteControllerFindMyFavorites(page, limit, sortBy, order, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვის წაშლა ფავორიტებიდან
     * @param {string} questionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public favoriteControllerRemoveFavorite(questionId: string, options?: RawAxiosRequestConfig) {
        return FavoritesApiFp(this.configuration).favoriteControllerRemoveFavorite(questionId, options).then((request) => request(this.axios, this.basePath));
    }
}

export const FavoriteControllerFindMyFavoritesOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type FavoriteControllerFindMyFavoritesOrderEnum = typeof FavoriteControllerFindMyFavoritesOrderEnum[keyof typeof FavoriteControllerFindMyFavoritesOrderEnum];
