/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { Favorite } from '../models';
/**
 * FavoritesApi - axios parameter creator
 * @export
 */
export declare const FavoritesApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @summary კითხვის დამატება ფავორიტებში
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerAddFavorite: (questionId: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary ჩემი ფავორიტი კითხვები (pagination-ით)
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {string} [order] დალაგების მიმართულება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerFindMyFavorites: (page?: number, limit?: number, sortBy?: string, order?: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary კითხვის წაშლა ფავორიტებიდან
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerRemoveFavorite: (questionId: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * FavoritesApi - functional programming interface
 * @export
 */
export declare const FavoritesApiFp: (configuration?: Configuration) => {
    /**
     *
     * @summary კითხვის დამატება ფავორიტებში
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerAddFavorite(questionId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
    /**
     *
     * @summary ჩემი ფავორიტი კითხვები (pagination-ით)
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {string} [order] დალაგების მიმართულება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerFindMyFavorites(page?: number, limit?: number, sortBy?: string, order?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>>;
    /**
     *
     * @summary კითხვის წაშლა ფავორიტებიდან
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerRemoveFavorite(questionId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Favorite>>>;
};
/**
 * FavoritesApi - factory interface
 * @export
 */
export declare const FavoritesApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @summary კითხვის დამატება ფავორიტებში
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerAddFavorite(questionId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary ჩემი ფავორიტი კითხვები (pagination-ით)
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {string} [order] დალაგების მიმართულება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerFindMyFavorites(page?: number, limit?: number, sortBy?: string, order?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary კითხვის წაშლა ფავორიტებიდან
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    favoriteControllerRemoveFavorite(questionId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Favorite>>;
};
/**
 * FavoritesApi - object-oriented interface
 * @export
 * @class FavoritesApi
 * @extends {BaseAPI}
 */
export declare class FavoritesApi extends BaseAPI {
    /**
     *
     * @summary კითხვის დამატება ფავორიტებში
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FavoritesApi
     */
    favoriteControllerAddFavorite(questionId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary ჩემი ფავორიტი კითხვები (pagination-ით)
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {string} [order] დალაგების მიმართულება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FavoritesApi
     */
    favoriteControllerFindMyFavorites(page?: number, limit?: number, sortBy?: string, order?: string, options?: AxiosRequestConfig): Promise<AxiosResponse<void>>;
    /**
     *
     * @summary კითხვის წაშლა ფავორიტებიდან
     * @param {string} questionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FavoritesApi
     */
    favoriteControllerRemoveFavorite(questionId: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Favorite>>;
}
