/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MarkAllReadResponseDto } from '../models';
// @ts-ignore
import type { NotificationDetailResponseDto } from '../models';
// @ts-ignore
import type { UnreadCountResponseDto } from '../models';
/**
 * NotificationsApi - axios parameter creator
 */
export const NotificationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ჩემი შეტყობინებების paginated სია (dropdown)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {NotificationsUserControllerFindAllOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsUserControllerFindAll: async (page?: number, limit?: number, sortBy?: string, order?: NotificationsUserControllerFindAllOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary შეტყობინების სრული content (მოდალი) + auto mark-as-read
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsUserControllerFindOne: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('notificationsUserControllerFindOne', 'id', id)
            const localVarPath = `/notifications/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary წაუკითხავი შეტყობინებების რაოდენობა (bell badge)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsUserControllerGetUnreadCount: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notifications/unread-count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ჩემი ყველა შეტყობინების მონიშვნა წაკითხულად
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsUserControllerMarkAllRead: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/notifications/read-all`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationsApi - functional programming interface
 */
export const NotificationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary ჩემი შეტყობინებების paginated სია (dropdown)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {NotificationsUserControllerFindAllOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationsUserControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: NotificationsUserControllerFindAllOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationsUserControllerFindAll(page, limit, sortBy, order, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.notificationsUserControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary შეტყობინების სრული content (მოდალი) + auto mark-as-read
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationsUserControllerFindOne(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationDetailResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationsUserControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.notificationsUserControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary წაუკითხავი შეტყობინებების რაოდენობა (bell badge)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationsUserControllerGetUnreadCount(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UnreadCountResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationsUserControllerGetUnreadCount(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.notificationsUserControllerGetUnreadCount']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ჩემი ყველა შეტყობინების მონიშვნა წაკითხულად
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async notificationsUserControllerMarkAllRead(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MarkAllReadResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.notificationsUserControllerMarkAllRead(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationsApi.notificationsUserControllerMarkAllRead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationsApi - factory interface
 */
export const NotificationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationsApiFp(configuration)
    return {
        /**
         * 
         * @summary ჩემი შეტყობინებების paginated სია (dropdown)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {NotificationsUserControllerFindAllOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsUserControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: NotificationsUserControllerFindAllOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.notificationsUserControllerFindAll(page, limit, sortBy, order, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary შეტყობინების სრული content (მოდალი) + auto mark-as-read
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsUserControllerFindOne(id: number, options?: RawAxiosRequestConfig): AxiosPromise<NotificationDetailResponseDto> {
            return localVarFp.notificationsUserControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary წაუკითხავი შეტყობინებების რაოდენობა (bell badge)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsUserControllerGetUnreadCount(options?: RawAxiosRequestConfig): AxiosPromise<UnreadCountResponseDto> {
            return localVarFp.notificationsUserControllerGetUnreadCount(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ჩემი ყველა შეტყობინების მონიშვნა წაკითხულად
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        notificationsUserControllerMarkAllRead(options?: RawAxiosRequestConfig): AxiosPromise<MarkAllReadResponseDto> {
            return localVarFp.notificationsUserControllerMarkAllRead(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationsApi - object-oriented interface
 */
export class NotificationsApi extends BaseAPI {
    /**
     * 
     * @summary ჩემი შეტყობინებების paginated სია (dropdown)
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {NotificationsUserControllerFindAllOrderEnum} [order] დალაგების მიმართულება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public notificationsUserControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: NotificationsUserControllerFindAllOrderEnum, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).notificationsUserControllerFindAll(page, limit, sortBy, order, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary შეტყობინების სრული content (მოდალი) + auto mark-as-read
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public notificationsUserControllerFindOne(id: number, options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).notificationsUserControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary წაუკითხავი შეტყობინებების რაოდენობა (bell badge)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public notificationsUserControllerGetUnreadCount(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).notificationsUserControllerGetUnreadCount(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ჩემი ყველა შეტყობინების მონიშვნა წაკითხულად
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public notificationsUserControllerMarkAllRead(options?: RawAxiosRequestConfig) {
        return NotificationsApiFp(this.configuration).notificationsUserControllerMarkAllRead(options).then((request) => request(this.axios, this.basePath));
    }
}

export const NotificationsUserControllerFindAllOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type NotificationsUserControllerFindAllOrderEnum = typeof NotificationsUserControllerFindAllOrderEnum[keyof typeof NotificationsUserControllerFindAllOrderEnum];
