/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SendEmailOtpDto } from '../models';
// @ts-ignore
import type { SendOtpDto } from '../models';
// @ts-ignore
import type { SendOtpResponseDto } from '../models';
// @ts-ignore
import type { VerifyEmailOtpDto } from '../models';
// @ts-ignore
import type { VerifyOtpDto } from '../models';
/**
 * OtpApi - axios parameter creator
 */
export const OtpApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary OTP კოდის გაგზავნა მითითებულ ელფოსტაზე
         * @param {SendEmailOtpDto} sendEmailOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otpControllerSendEmailOtp: async (sendEmailOtpDto: SendEmailOtpDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendEmailOtpDto' is not null or undefined
            assertParamExists('otpControllerSendEmailOtp', 'sendEmailOtpDto', sendEmailOtpDto)
            const localVarPath = `/otp/send-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendEmailOtpDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary OTP კოდის გაგზავნა მითითებულ მობილურზე
         * @param {SendOtpDto} sendOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otpControllerSendOtp: async (sendOtpDto: SendOtpDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendOtpDto' is not null or undefined
            assertParamExists('otpControllerSendOtp', 'sendOtpDto', sendOtpDto)
            const localVarPath = `/otp/send`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendOtpDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ელფოსტაზე გაგზავნილი OTP კოდის დადასტურება
         * @param {VerifyEmailOtpDto} verifyEmailOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otpControllerVerifyEmailOtp: async (verifyEmailOtpDto: VerifyEmailOtpDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verifyEmailOtpDto' is not null or undefined
            assertParamExists('otpControllerVerifyEmailOtp', 'verifyEmailOtpDto', verifyEmailOtpDto)
            const localVarPath = `/otp/verify-email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyEmailOtpDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary OTP კოდის დადასტურება
         * @param {VerifyOtpDto} verifyOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otpControllerVerifyOtp: async (verifyOtpDto: VerifyOtpDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'verifyOtpDto' is not null or undefined
            assertParamExists('otpControllerVerifyOtp', 'verifyOtpDto', verifyOtpDto)
            const localVarPath = `/otp/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(verifyOtpDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OtpApi - functional programming interface
 */
export const OtpApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OtpApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary OTP კოდის გაგზავნა მითითებულ ელფოსტაზე
         * @param {SendEmailOtpDto} sendEmailOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otpControllerSendEmailOtp(sendEmailOtpDto: SendEmailOtpDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SendOtpResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otpControllerSendEmailOtp(sendEmailOtpDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OtpApi.otpControllerSendEmailOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary OTP კოდის გაგზავნა მითითებულ მობილურზე
         * @param {SendOtpDto} sendOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otpControllerSendOtp(sendOtpDto: SendOtpDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SendOtpResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otpControllerSendOtp(sendOtpDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OtpApi.otpControllerSendOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ელფოსტაზე გაგზავნილი OTP კოდის დადასტურება
         * @param {VerifyEmailOtpDto} verifyEmailOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otpControllerVerifyEmailOtp(verifyEmailOtpDto: VerifyEmailOtpDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otpControllerVerifyEmailOtp(verifyEmailOtpDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OtpApi.otpControllerVerifyEmailOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary OTP კოდის დადასტურება
         * @param {VerifyOtpDto} verifyOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async otpControllerVerifyOtp(verifyOtpDto: VerifyOtpDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.otpControllerVerifyOtp(verifyOtpDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OtpApi.otpControllerVerifyOtp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OtpApi - factory interface
 */
export const OtpApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OtpApiFp(configuration)
    return {
        /**
         * 
         * @summary OTP კოდის გაგზავნა მითითებულ ელფოსტაზე
         * @param {SendEmailOtpDto} sendEmailOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otpControllerSendEmailOtp(sendEmailOtpDto: SendEmailOtpDto, options?: RawAxiosRequestConfig): AxiosPromise<SendOtpResponseDto> {
            return localVarFp.otpControllerSendEmailOtp(sendEmailOtpDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary OTP კოდის გაგზავნა მითითებულ მობილურზე
         * @param {SendOtpDto} sendOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otpControllerSendOtp(sendOtpDto: SendOtpDto, options?: RawAxiosRequestConfig): AxiosPromise<SendOtpResponseDto> {
            return localVarFp.otpControllerSendOtp(sendOtpDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ელფოსტაზე გაგზავნილი OTP კოდის დადასტურება
         * @param {VerifyEmailOtpDto} verifyEmailOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otpControllerVerifyEmailOtp(verifyEmailOtpDto: VerifyEmailOtpDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.otpControllerVerifyEmailOtp(verifyEmailOtpDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary OTP კოდის დადასტურება
         * @param {VerifyOtpDto} verifyOtpDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        otpControllerVerifyOtp(verifyOtpDto: VerifyOtpDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.otpControllerVerifyOtp(verifyOtpDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OtpApi - object-oriented interface
 */
export class OtpApi extends BaseAPI {
    /**
     * 
     * @summary OTP კოდის გაგზავნა მითითებულ ელფოსტაზე
     * @param {SendEmailOtpDto} sendEmailOtpDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public otpControllerSendEmailOtp(sendEmailOtpDto: SendEmailOtpDto, options?: RawAxiosRequestConfig) {
        return OtpApiFp(this.configuration).otpControllerSendEmailOtp(sendEmailOtpDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary OTP კოდის გაგზავნა მითითებულ მობილურზე
     * @param {SendOtpDto} sendOtpDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public otpControllerSendOtp(sendOtpDto: SendOtpDto, options?: RawAxiosRequestConfig) {
        return OtpApiFp(this.configuration).otpControllerSendOtp(sendOtpDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ელფოსტაზე გაგზავნილი OTP კოდის დადასტურება
     * @param {VerifyEmailOtpDto} verifyEmailOtpDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public otpControllerVerifyEmailOtp(verifyEmailOtpDto: VerifyEmailOtpDto, options?: RawAxiosRequestConfig) {
        return OtpApiFp(this.configuration).otpControllerVerifyEmailOtp(verifyEmailOtpDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary OTP კოდის დადასტურება
     * @param {VerifyOtpDto} verifyOtpDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public otpControllerVerifyOtp(verifyOtpDto: VerifyOtpDto, options?: RawAxiosRequestConfig) {
        return OtpApiFp(this.configuration).otpControllerVerifyOtp(verifyOtpDto, options).then((request) => request(this.axios, this.basePath));
    }
}

