/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * PaymentsApi - axios parameter creator
 */
export const PaymentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary BOG-ის გადახდის callback (არაავტორიზებული, ხელმოწერით დაცული)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentsControllerBogCallback: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/payments/callback/bog`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary MockPaymentProvider-ის auto-complete (მხოლოდ PAYMENT_PROVIDER=mock)
         * @param {string} externalId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentsControllerCompleteMockPayment: async (externalId: string, orderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'externalId' is not null or undefined
            assertParamExists('paymentsControllerCompleteMockPayment', 'externalId', externalId)
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('paymentsControllerCompleteMockPayment', 'orderId', orderId)
            const localVarPath = `/payments/mock/{externalId}/complete`
                .replace('{externalId}', encodeURIComponent(String(externalId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (orderId !== undefined) {
                localVarQueryParameter['orderId'] = orderId;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary BOG გადახდის დაწყება კონკრეტული შეკვეთისთვის
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentsControllerInitiate: async (orderId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'orderId' is not null or undefined
            assertParamExists('paymentsControllerInitiate', 'orderId', orderId)
            const localVarPath = `/payments/{orderId}/initiate`
                .replace('{orderId}', encodeURIComponent(String(orderId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PaymentsApi - functional programming interface
 */
export const PaymentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PaymentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary BOG-ის გადახდის callback (არაავტორიზებული, ხელმოწერით დაცული)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentsControllerBogCallback(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentsControllerBogCallback(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.paymentsControllerBogCallback']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary MockPaymentProvider-ის auto-complete (მხოლოდ PAYMENT_PROVIDER=mock)
         * @param {string} externalId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentsControllerCompleteMockPayment(externalId: string, orderId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentsControllerCompleteMockPayment(externalId, orderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.paymentsControllerCompleteMockPayment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary BOG გადახდის დაწყება კონკრეტული შეკვეთისთვის
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async paymentsControllerInitiate(orderId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.paymentsControllerInitiate(orderId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PaymentsApi.paymentsControllerInitiate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PaymentsApi - factory interface
 */
export const PaymentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PaymentsApiFp(configuration)
    return {
        /**
         * 
         * @summary BOG-ის გადახდის callback (არაავტორიზებული, ხელმოწერით დაცული)
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentsControllerBogCallback(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.paymentsControllerBogCallback(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary MockPaymentProvider-ის auto-complete (მხოლოდ PAYMENT_PROVIDER=mock)
         * @param {string} externalId 
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentsControllerCompleteMockPayment(externalId: string, orderId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.paymentsControllerCompleteMockPayment(externalId, orderId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary BOG გადახდის დაწყება კონკრეტული შეკვეთისთვის
         * @param {string} orderId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        paymentsControllerInitiate(orderId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.paymentsControllerInitiate(orderId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * PaymentsApi - object-oriented interface
 */
export class PaymentsApi extends BaseAPI {
    /**
     * 
     * @summary BOG-ის გადახდის callback (არაავტორიზებული, ხელმოწერით დაცული)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public paymentsControllerBogCallback(options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).paymentsControllerBogCallback(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary MockPaymentProvider-ის auto-complete (მხოლოდ PAYMENT_PROVIDER=mock)
     * @param {string} externalId 
     * @param {string} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public paymentsControllerCompleteMockPayment(externalId: string, orderId: string, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).paymentsControllerCompleteMockPayment(externalId, orderId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary BOG გადახდის დაწყება კონკრეტული შეკვეთისთვის
     * @param {string} orderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public paymentsControllerInitiate(orderId: string, options?: RawAxiosRequestConfig) {
        return PaymentsApiFp(this.configuration).paymentsControllerInitiate(orderId, options).then((request) => request(this.axios, this.basePath));
    }
}

