/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateProductDto } from '../models';
// @ts-ignore
import type { ProductResponseDto } from '../models';
// @ts-ignore
import type { SetProductAttributeValuesDto } from '../models';
// @ts-ignore
import type { UpdateProductDto } from '../models';
/**
 * ProductsApi - axios parameter creator
 */
export const ProductsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ახალი პროდუქტის შექმნა (ADMIN)
         * @param {CreateProductDto} createProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerCreate: async (createProductDto: CreateProductDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createProductDto' is not null or undefined
            assertParamExists('productsControllerCreate', 'createProductDto', createProductDto)
            const localVarPath = `/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createProductDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary პროდუქტების სია — ძიება, ფილტრები, პაგინაცია
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {ProductsControllerFindAllOrderEnum} [order] დალაგების მიმართულება
         * @param {string} [search] საძიებო ტექსტი — ეძებს name და description ველებში
         * @param {string} [categoryId] გაფილტვრა კატეგორიის მიხედვით
         * @param {number} [minPrice] მინიმალური ფასი
         * @param {number} [maxPrice] მაქსიმალური ფასი
         * @param {boolean} [isActive] გაფილტვრა აქტიურობის მიხედვით
         * @param {boolean} [hasDiscount] გაფილტვრა ფასდაკლების მიხედვით — true: მხოლოდ ფასდაკლებიანი, false: მხოლოდ ფასდაკლების გარეშე
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerFindAll: async (page?: number, limit?: number, sortBy?: string, order?: ProductsControllerFindAllOrderEnum, search?: string, categoryId?: string, minPrice?: number, maxPrice?: number, isActive?: boolean, hasDiscount?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/products`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (search !== undefined) {
                localVarQueryParameter['search'] = search;
            }

            if (categoryId !== undefined) {
                localVarQueryParameter['categoryId'] = categoryId;
            }

            if (minPrice !== undefined) {
                localVarQueryParameter['minPrice'] = minPrice;
            }

            if (maxPrice !== undefined) {
                localVarQueryParameter['maxPrice'] = maxPrice;
            }

            if (isActive !== undefined) {
                localVarQueryParameter['isActive'] = isActive;
            }

            if (hasDiscount !== undefined) {
                localVarQueryParameter['hasDiscount'] = hasDiscount;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კონკრეტული პროდუქტის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productsControllerFindOne', 'id', id)
            const localVarPath = `/products/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary პროდუქტის attribute value-ების სია
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerGetAttributeValues: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productsControllerGetAttributeValues', 'id', id)
            const localVarPath = `/products/{id}/attribute-values`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary პროდუქტის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productsControllerRemove', 'id', id)
            const localVarPath = `/products/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary პროდუქტის attribute value-ების bulk set (ADMIN) — მთლიანად ანაცვლებს არსებულს
         * @param {string} id 
         * @param {SetProductAttributeValuesDto} setProductAttributeValuesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerSetAttributeValues: async (id: string, setProductAttributeValuesDto: SetProductAttributeValuesDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productsControllerSetAttributeValues', 'id', id)
            // verify required parameter 'setProductAttributeValuesDto' is not null or undefined
            assertParamExists('productsControllerSetAttributeValues', 'setProductAttributeValuesDto', setProductAttributeValuesDto)
            const localVarPath = `/products/{id}/attribute-values`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setProductAttributeValuesDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary პროდუქტის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateProductDto} updateProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerUpdate: async (id: string, updateProductDto: UpdateProductDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('productsControllerUpdate', 'id', id)
            // verify required parameter 'updateProductDto' is not null or undefined
            assertParamExists('productsControllerUpdate', 'updateProductDto', updateProductDto)
            const localVarPath = `/products/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateProductDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProductsApi - functional programming interface
 */
export const ProductsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProductsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary ახალი პროდუქტის შექმნა (ADMIN)
         * @param {CreateProductDto} createProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsControllerCreate(createProductDto: CreateProductDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsControllerCreate(createProductDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productsControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary პროდუქტების სია — ძიება, ფილტრები, პაგინაცია
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {ProductsControllerFindAllOrderEnum} [order] დალაგების მიმართულება
         * @param {string} [search] საძიებო ტექსტი — ეძებს name და description ველებში
         * @param {string} [categoryId] გაფილტვრა კატეგორიის მიხედვით
         * @param {number} [minPrice] მინიმალური ფასი
         * @param {number} [maxPrice] მაქსიმალური ფასი
         * @param {boolean} [isActive] გაფილტვრა აქტიურობის მიხედვით
         * @param {boolean} [hasDiscount] გაფილტვრა ფასდაკლების მიხედვით — true: მხოლოდ ფასდაკლებიანი, false: მხოლოდ ფასდაკლების გარეშე
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: ProductsControllerFindAllOrderEnum, search?: string, categoryId?: string, minPrice?: number, maxPrice?: number, isActive?: boolean, hasDiscount?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsControllerFindAll(page, limit, sortBy, order, search, categoryId, minPrice, maxPrice, isActive, hasDiscount, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productsControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კონკრეტული პროდუქტის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productsControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary პროდუქტის attribute value-ების სია
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsControllerGetAttributeValues(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsControllerGetAttributeValues(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productsControllerGetAttributeValues']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary პროდუქტის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productsControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary პროდუქტის attribute value-ების bulk set (ADMIN) — მთლიანად ანაცვლებს არსებულს
         * @param {string} id 
         * @param {SetProductAttributeValuesDto} setProductAttributeValuesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsControllerSetAttributeValues(id: string, setProductAttributeValuesDto: SetProductAttributeValuesDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsControllerSetAttributeValues(id, setProductAttributeValuesDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productsControllerSetAttributeValues']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary პროდუქტის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateProductDto} updateProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async productsControllerUpdate(id: string, updateProductDto: UpdateProductDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProductResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.productsControllerUpdate(id, updateProductDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProductsApi.productsControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProductsApi - factory interface
 */
export const ProductsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProductsApiFp(configuration)
    return {
        /**
         * 
         * @summary ახალი პროდუქტის შექმნა (ADMIN)
         * @param {CreateProductDto} createProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerCreate(createProductDto: CreateProductDto, options?: RawAxiosRequestConfig): AxiosPromise<ProductResponseDto> {
            return localVarFp.productsControllerCreate(createProductDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary პროდუქტების სია — ძიება, ფილტრები, პაგინაცია
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {ProductsControllerFindAllOrderEnum} [order] დალაგების მიმართულება
         * @param {string} [search] საძიებო ტექსტი — ეძებს name და description ველებში
         * @param {string} [categoryId] გაფილტვრა კატეგორიის მიხედვით
         * @param {number} [minPrice] მინიმალური ფასი
         * @param {number} [maxPrice] მაქსიმალური ფასი
         * @param {boolean} [isActive] გაფილტვრა აქტიურობის მიხედვით
         * @param {boolean} [hasDiscount] გაფილტვრა ფასდაკლების მიხედვით — true: მხოლოდ ფასდაკლებიანი, false: მხოლოდ ფასდაკლების გარეშე
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: ProductsControllerFindAllOrderEnum, search?: string, categoryId?: string, minPrice?: number, maxPrice?: number, isActive?: boolean, hasDiscount?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.productsControllerFindAll(page, limit, sortBy, order, search, categoryId, minPrice, maxPrice, isActive, hasDiscount, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კონკრეტული პროდუქტის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.productsControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary პროდუქტის attribute value-ების სია
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerGetAttributeValues(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.productsControllerGetAttributeValues(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary პროდუქტის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.productsControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary პროდუქტის attribute value-ების bulk set (ADMIN) — მთლიანად ანაცვლებს არსებულს
         * @param {string} id 
         * @param {SetProductAttributeValuesDto} setProductAttributeValuesDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerSetAttributeValues(id: string, setProductAttributeValuesDto: SetProductAttributeValuesDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.productsControllerSetAttributeValues(id, setProductAttributeValuesDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary პროდუქტის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateProductDto} updateProductDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        productsControllerUpdate(id: string, updateProductDto: UpdateProductDto, options?: RawAxiosRequestConfig): AxiosPromise<ProductResponseDto> {
            return localVarFp.productsControllerUpdate(id, updateProductDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProductsApi - object-oriented interface
 */
export class ProductsApi extends BaseAPI {
    /**
     * 
     * @summary ახალი პროდუქტის შექმნა (ADMIN)
     * @param {CreateProductDto} createProductDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsControllerCreate(createProductDto: CreateProductDto, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productsControllerCreate(createProductDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary პროდუქტების სია — ძიება, ფილტრები, პაგინაცია
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {ProductsControllerFindAllOrderEnum} [order] დალაგების მიმართულება
     * @param {string} [search] საძიებო ტექსტი — ეძებს name და description ველებში
     * @param {string} [categoryId] გაფილტვრა კატეგორიის მიხედვით
     * @param {number} [minPrice] მინიმალური ფასი
     * @param {number} [maxPrice] მაქსიმალური ფასი
     * @param {boolean} [isActive] გაფილტვრა აქტიურობის მიხედვით
     * @param {boolean} [hasDiscount] გაფილტვრა ფასდაკლების მიხედვით — true: მხოლოდ ფასდაკლებიანი, false: მხოლოდ ფასდაკლების გარეშე
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: ProductsControllerFindAllOrderEnum, search?: string, categoryId?: string, minPrice?: number, maxPrice?: number, isActive?: boolean, hasDiscount?: boolean, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productsControllerFindAll(page, limit, sortBy, order, search, categoryId, minPrice, maxPrice, isActive, hasDiscount, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კონკრეტული პროდუქტის მიღება
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productsControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary პროდუქტის attribute value-ების სია
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsControllerGetAttributeValues(id: string, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productsControllerGetAttributeValues(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary პროდუქტის წაშლა (ADMIN)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productsControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary პროდუქტის attribute value-ების bulk set (ADMIN) — მთლიანად ანაცვლებს არსებულს
     * @param {string} id 
     * @param {SetProductAttributeValuesDto} setProductAttributeValuesDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsControllerSetAttributeValues(id: string, setProductAttributeValuesDto: SetProductAttributeValuesDto, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productsControllerSetAttributeValues(id, setProductAttributeValuesDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary პროდუქტის განახლება (ADMIN)
     * @param {string} id 
     * @param {UpdateProductDto} updateProductDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public productsControllerUpdate(id: string, updateProductDto: UpdateProductDto, options?: RawAxiosRequestConfig) {
        return ProductsApiFp(this.configuration).productsControllerUpdate(id, updateProductDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export const ProductsControllerFindAllOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type ProductsControllerFindAllOrderEnum = typeof ProductsControllerFindAllOrderEnum[keyof typeof ProductsControllerFindAllOrderEnum];
