/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
import { RequestArgs, BaseAPI } from '../base';
import { CreateQuestionDto } from '../models';
import { Question } from '../models';
import { UpdateQuestionDto } from '../models';
/**
 * QuestionsApi - axios parameter creator
 * @export
 */
export declare const QuestionsApiAxiosParamCreator: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateQuestionDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerCreate: (body: CreateQuestionDto, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @summary ყველა კითხვა (ფილტრით)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerFindAll: (options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerFindOne: (id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerRemove: (id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
    /**
     *
     * @param {UpdateQuestionDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerUpdate: (body: UpdateQuestionDto, id: string, options?: AxiosRequestConfig) => Promise<RequestArgs>;
};
/**
 * QuestionsApi - functional programming interface
 * @export
 */
export declare const QuestionsApiFp: (configuration?: Configuration) => {
    /**
     *
     * @param {CreateQuestionDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerCreate(body: CreateQuestionDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Question>>>;
    /**
     *
     * @summary ყველა კითხვა (ფილტრით)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerFindAll(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Question>>>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Question>>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerRemove(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Question>>>;
    /**
     *
     * @param {UpdateQuestionDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerUpdate(body: UpdateQuestionDto, id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Question>>>;
};
/**
 * QuestionsApi - factory interface
 * @export
 */
export declare const QuestionsApiFactory: (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) => {
    /**
     *
     * @param {CreateQuestionDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerCreate(body: CreateQuestionDto, options?: AxiosRequestConfig): Promise<AxiosResponse<Question>>;
    /**
     *
     * @summary ყველა კითხვა (ფილტრით)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerFindAll(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Question>>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Question>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerRemove(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Question>>;
    /**
     *
     * @param {UpdateQuestionDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    questionControllerUpdate(body: UpdateQuestionDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Question>>;
};
/**
 * QuestionsApi - object-oriented interface
 * @export
 * @class QuestionsApi
 * @extends {BaseAPI}
 */
export declare class QuestionsApi extends BaseAPI {
    /**
     *
     * @param {CreateQuestionDto} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    questionControllerCreate(body: CreateQuestionDto, options?: AxiosRequestConfig): Promise<AxiosResponse<Question>>;
    /**
     *
     * @summary ყველა კითხვა (ფილტრით)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    questionControllerFindAll(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Question>>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    questionControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Question>>;
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    questionControllerRemove(id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Question>>;
    /**
     *
     * @param {UpdateQuestionDto} body
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuestionsApi
     */
    questionControllerUpdate(body: UpdateQuestionDto, id: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Question>>;
}
