/* tslint:disable */
/* eslint-disable */
/**
 * My First Nest API
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApproveQuestionDto } from '../models';
// @ts-ignore
import type { CreateQuestionDto } from '../models';
// @ts-ignore
import type { PaginatedResponseDto } from '../models';
// @ts-ignore
import type { Question } from '../models';
// @ts-ignore
import type { RejectQuestionDto } from '../models';
// @ts-ignore
import type { UpdateQuestionDto } from '../models';
/**
 * QuestionsApi - axios parameter creator
 */
export const QuestionsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary კითხვის გააქტიურება (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerActivate: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerActivate', 'id', id)
            const localVarPath = `/questions/{id}/activate`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary user-ის დასმული კითხვის დადასტურება, სურვილისამებრ დამთავრების თარიღით (მხოლოდ admin)
         * @param {string} id 
         * @param {ApproveQuestionDto} approveQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerApprove: async (id: string, approveQuestionDto: ApproveQuestionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerApprove', 'id', id)
            // verify required parameter 'approveQuestionDto' is not null or undefined
            assertParamExists('questionControllerApprove', 'approveQuestionDto', approveQuestionDto)
            const localVarPath = `/questions/{id}/approve`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(approveQuestionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვის დამატება (user-ს დღეში 1-ხელ, ერთი მოწყობილობიდან; user-ის კითხვა isActive:false/PENDING იქმნება)
         * @param {CreateQuestionDto} createQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerCreate: async (createQuestionDto: CreateQuestionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createQuestionDto' is not null or undefined
            assertParamExists('questionControllerCreate', 'createQuestionDto', createQuestionDto)
            const localVarPath = `/questions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createQuestionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვის დეაქტივაცია (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerDeactivate: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerDeactivate', 'id', id)
            const localVarPath = `/questions/{id}/deactivate`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ყველა კითხვა (pagination, ფილტრით)
         * @param {number} [page] გვერდის ნომერი
         * @param {number} [limit] ჩანაწერები გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {QuestionControllerFindAllOrderEnum} [order] მიმართულება
         * @param {number} [category] კატეგორიის ID
         * @param {QuestionControllerFindAllStatusEnum} [status] აქტიურობის სტატუსი (ვადაგასული კითხვები ავტომატურად ითვლება inactive-ად)
         * @param {QuestionControllerFindAllApprovalStatusEnum} [approvalStatus] admin-ის განხილვის სტატუსი
         * @param {QuestionControllerFindAllCreatorTypeEnum} [creatorType] ვინ დასვა კითხვა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerFindAll: async (page?: number, limit?: number, sortBy?: string, order?: QuestionControllerFindAllOrderEnum, category?: number, status?: QuestionControllerFindAllStatusEnum, approvalStatus?: QuestionControllerFindAllApprovalStatusEnum, creatorType?: QuestionControllerFindAllCreatorTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/questions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (approvalStatus !== undefined) {
                localVarQueryParameter['approvalStatus'] = approvalStatus;
            }

            if (creatorType !== undefined) {
                localVarQueryParameter['creatorType'] = creatorType;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ჩემ მიერ დასმული კითხვების სია (პროფილის გვერდისთვის, admin-ის დასტურის სტატუსით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {QuestionControllerFindMyQuestionsOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerFindMyQuestions: async (page?: number, limit?: number, sortBy?: string, order?: QuestionControllerFindMyQuestionsOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/questions/my-questions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerFindOne', 'id', id)
            const localVarPath = `/questions/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვის დაპინვა მთავარ გვერდზე, როგორც მნიშვნელოვანი (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerPin: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerPin', 'id', id)
            const localVarPath = `/questions/{id}/pin`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary user-ის დასმული კითხვის უკუგდება მიზეზის მითითებით (მხოლოდ admin)
         * @param {string} id 
         * @param {RejectQuestionDto} rejectQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerReject: async (id: string, rejectQuestionDto: RejectQuestionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerReject', 'id', id)
            // verify required parameter 'rejectQuestionDto' is not null or undefined
            assertParamExists('questionControllerReject', 'rejectQuestionDto', rejectQuestionDto)
            const localVarPath = `/questions/{id}/reject`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rejectQuestionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვის წაშლა (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerRemove', 'id', id)
            const localVarPath = `/questions/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვის დაპინვის გაუქმება (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerUnpin: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerUnpin', 'id', id)
            const localVarPath = `/questions/{id}/unpin`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვის რედაქტირება, მათ შორის user-ის დასმული კითხვის ტექსტის/პასუხების ცვლილება (მხოლოდ admin)
         * @param {string} id 
         * @param {UpdateQuestionDto} updateQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerUpdate: async (id: string, updateQuestionDto: UpdateQuestionDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('questionControllerUpdate', 'id', id)
            // verify required parameter 'updateQuestionDto' is not null or undefined
            assertParamExists('questionControllerUpdate', 'updateQuestionDto', updateQuestionDto)
            const localVarPath = `/questions/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateQuestionDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuestionsApi - functional programming interface
 */
export const QuestionsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuestionsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary კითხვის გააქტიურება (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerActivate(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerActivate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerActivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary user-ის დასმული კითხვის დადასტურება, სურვილისამებრ დამთავრების თარიღით (მხოლოდ admin)
         * @param {string} id 
         * @param {ApproveQuestionDto} approveQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerApprove(id: string, approveQuestionDto: ApproveQuestionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerApprove(id, approveQuestionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerApprove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვის დამატება (user-ს დღეში 1-ხელ, ერთი მოწყობილობიდან; user-ის კითხვა isActive:false/PENDING იქმნება)
         * @param {CreateQuestionDto} createQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerCreate(createQuestionDto: CreateQuestionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerCreate(createQuestionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვის დეაქტივაცია (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerDeactivate(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerDeactivate(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerDeactivate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ყველა კითხვა (pagination, ფილტრით)
         * @param {number} [page] გვერდის ნომერი
         * @param {number} [limit] ჩანაწერები გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {QuestionControllerFindAllOrderEnum} [order] მიმართულება
         * @param {number} [category] კატეგორიის ID
         * @param {QuestionControllerFindAllStatusEnum} [status] აქტიურობის სტატუსი (ვადაგასული კითხვები ავტომატურად ითვლება inactive-ად)
         * @param {QuestionControllerFindAllApprovalStatusEnum} [approvalStatus] admin-ის განხილვის სტატუსი
         * @param {QuestionControllerFindAllCreatorTypeEnum} [creatorType] ვინ დასვა კითხვა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: QuestionControllerFindAllOrderEnum, category?: number, status?: QuestionControllerFindAllStatusEnum, approvalStatus?: QuestionControllerFindAllApprovalStatusEnum, creatorType?: QuestionControllerFindAllCreatorTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerFindAll(page, limit, sortBy, order, category, status, approvalStatus, creatorType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ჩემ მიერ დასმული კითხვების სია (პროფილის გვერდისთვის, admin-ის დასტურის სტატუსით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {QuestionControllerFindMyQuestionsOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerFindMyQuestions(page?: number, limit?: number, sortBy?: string, order?: QuestionControllerFindMyQuestionsOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerFindMyQuestions(page, limit, sortBy, order, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerFindMyQuestions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვის დაპინვა მთავარ გვერდზე, როგორც მნიშვნელოვანი (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerPin(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerPin(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerPin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary user-ის დასმული კითხვის უკუგდება მიზეზის მითითებით (მხოლოდ admin)
         * @param {string} id 
         * @param {RejectQuestionDto} rejectQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerReject(id: string, rejectQuestionDto: RejectQuestionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerReject(id, rejectQuestionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerReject']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვის წაშლა (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვის დაპინვის გაუქმება (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerUnpin(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerUnpin(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerUnpin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვის რედაქტირება, მათ შორის user-ის დასმული კითხვის ტექსტის/პასუხების ცვლილება (მხოლოდ admin)
         * @param {string} id 
         * @param {UpdateQuestionDto} updateQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async questionControllerUpdate(id: string, updateQuestionDto: UpdateQuestionDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Question>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.questionControllerUpdate(id, updateQuestionDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['QuestionsApi.questionControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * QuestionsApi - factory interface
 */
export const QuestionsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuestionsApiFp(configuration)
    return {
        /**
         * 
         * @summary კითხვის გააქტიურება (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerActivate(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerActivate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary user-ის დასმული კითხვის დადასტურება, სურვილისამებრ დამთავრების თარიღით (მხოლოდ admin)
         * @param {string} id 
         * @param {ApproveQuestionDto} approveQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerApprove(id: string, approveQuestionDto: ApproveQuestionDto, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerApprove(id, approveQuestionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვის დამატება (user-ს დღეში 1-ხელ, ერთი მოწყობილობიდან; user-ის კითხვა isActive:false/PENDING იქმნება)
         * @param {CreateQuestionDto} createQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerCreate(createQuestionDto: CreateQuestionDto, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerCreate(createQuestionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვის დეაქტივაცია (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerDeactivate(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerDeactivate(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ყველა კითხვა (pagination, ფილტრით)
         * @param {number} [page] გვერდის ნომერი
         * @param {number} [limit] ჩანაწერები გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {QuestionControllerFindAllOrderEnum} [order] მიმართულება
         * @param {number} [category] კატეგორიის ID
         * @param {QuestionControllerFindAllStatusEnum} [status] აქტიურობის სტატუსი (ვადაგასული კითხვები ავტომატურად ითვლება inactive-ად)
         * @param {QuestionControllerFindAllApprovalStatusEnum} [approvalStatus] admin-ის განხილვის სტატუსი
         * @param {QuestionControllerFindAllCreatorTypeEnum} [creatorType] ვინ დასვა კითხვა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: QuestionControllerFindAllOrderEnum, category?: number, status?: QuestionControllerFindAllStatusEnum, approvalStatus?: QuestionControllerFindAllApprovalStatusEnum, creatorType?: QuestionControllerFindAllCreatorTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedResponseDto> {
            return localVarFp.questionControllerFindAll(page, limit, sortBy, order, category, status, approvalStatus, creatorType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ჩემ მიერ დასმული კითხვების სია (პროფილის გვერდისთვის, admin-ის დასტურის სტატუსით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {QuestionControllerFindMyQuestionsOrderEnum} [order] დალაგების მიმართულება
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerFindMyQuestions(page?: number, limit?: number, sortBy?: string, order?: QuestionControllerFindMyQuestionsOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.questionControllerFindMyQuestions(page, limit, sortBy, order, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვის დაპინვა მთავარ გვერდზე, როგორც მნიშვნელოვანი (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerPin(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerPin(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary user-ის დასმული კითხვის უკუგდება მიზეზის მითითებით (მხოლოდ admin)
         * @param {string} id 
         * @param {RejectQuestionDto} rejectQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerReject(id: string, rejectQuestionDto: RejectQuestionDto, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerReject(id, rejectQuestionDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვის წაშლა (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვის დაპინვის გაუქმება (მხოლოდ admin)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerUnpin(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerUnpin(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვის რედაქტირება, მათ შორის user-ის დასმული კითხვის ტექსტის/პასუხების ცვლილება (მხოლოდ admin)
         * @param {string} id 
         * @param {UpdateQuestionDto} updateQuestionDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        questionControllerUpdate(id: string, updateQuestionDto: UpdateQuestionDto, options?: RawAxiosRequestConfig): AxiosPromise<Question> {
            return localVarFp.questionControllerUpdate(id, updateQuestionDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * QuestionsApi - object-oriented interface
 */
export class QuestionsApi extends BaseAPI {
    /**
     * 
     * @summary კითხვის გააქტიურება (მხოლოდ admin)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerActivate(id: string, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerActivate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary user-ის დასმული კითხვის დადასტურება, სურვილისამებრ დამთავრების თარიღით (მხოლოდ admin)
     * @param {string} id 
     * @param {ApproveQuestionDto} approveQuestionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerApprove(id: string, approveQuestionDto: ApproveQuestionDto, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerApprove(id, approveQuestionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვის დამატება (user-ს დღეში 1-ხელ, ერთი მოწყობილობიდან; user-ის კითხვა isActive:false/PENDING იქმნება)
     * @param {CreateQuestionDto} createQuestionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerCreate(createQuestionDto: CreateQuestionDto, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerCreate(createQuestionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვის დეაქტივაცია (მხოლოდ admin)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerDeactivate(id: string, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerDeactivate(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ყველა კითხვა (pagination, ფილტრით)
     * @param {number} [page] გვერდის ნომერი
     * @param {number} [limit] ჩანაწერები გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {QuestionControllerFindAllOrderEnum} [order] მიმართულება
     * @param {number} [category] კატეგორიის ID
     * @param {QuestionControllerFindAllStatusEnum} [status] აქტიურობის სტატუსი (ვადაგასული კითხვები ავტომატურად ითვლება inactive-ად)
     * @param {QuestionControllerFindAllApprovalStatusEnum} [approvalStatus] admin-ის განხილვის სტატუსი
     * @param {QuestionControllerFindAllCreatorTypeEnum} [creatorType] ვინ დასვა კითხვა
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerFindAll(page?: number, limit?: number, sortBy?: string, order?: QuestionControllerFindAllOrderEnum, category?: number, status?: QuestionControllerFindAllStatusEnum, approvalStatus?: QuestionControllerFindAllApprovalStatusEnum, creatorType?: QuestionControllerFindAllCreatorTypeEnum, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerFindAll(page, limit, sortBy, order, category, status, approvalStatus, creatorType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ჩემ მიერ დასმული კითხვების სია (პროფილის გვერდისთვის, admin-ის დასტურის სტატუსით)
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {QuestionControllerFindMyQuestionsOrderEnum} [order] დალაგების მიმართულება
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerFindMyQuestions(page?: number, limit?: number, sortBy?: string, order?: QuestionControllerFindMyQuestionsOrderEnum, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerFindMyQuestions(page, limit, sortBy, order, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვის დაპინვა მთავარ გვერდზე, როგორც მნიშვნელოვანი (მხოლოდ admin)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerPin(id: string, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerPin(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary user-ის დასმული კითხვის უკუგდება მიზეზის მითითებით (მხოლოდ admin)
     * @param {string} id 
     * @param {RejectQuestionDto} rejectQuestionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerReject(id: string, rejectQuestionDto: RejectQuestionDto, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerReject(id, rejectQuestionDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვის წაშლა (მხოლოდ admin)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვის დაპინვის გაუქმება (მხოლოდ admin)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerUnpin(id: string, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerUnpin(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვის რედაქტირება, მათ შორის user-ის დასმული კითხვის ტექსტის/პასუხების ცვლილება (მხოლოდ admin)
     * @param {string} id 
     * @param {UpdateQuestionDto} updateQuestionDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public questionControllerUpdate(id: string, updateQuestionDto: UpdateQuestionDto, options?: RawAxiosRequestConfig) {
        return QuestionsApiFp(this.configuration).questionControllerUpdate(id, updateQuestionDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export const QuestionControllerFindAllOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type QuestionControllerFindAllOrderEnum = typeof QuestionControllerFindAllOrderEnum[keyof typeof QuestionControllerFindAllOrderEnum];
export const QuestionControllerFindAllStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
} as const;
export type QuestionControllerFindAllStatusEnum = typeof QuestionControllerFindAllStatusEnum[keyof typeof QuestionControllerFindAllStatusEnum];
export const QuestionControllerFindAllApprovalStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected',
} as const;
export type QuestionControllerFindAllApprovalStatusEnum = typeof QuestionControllerFindAllApprovalStatusEnum[keyof typeof QuestionControllerFindAllApprovalStatusEnum];
export const QuestionControllerFindAllCreatorTypeEnum = {
    Admin: 'admin',
    User: 'user',
} as const;
export type QuestionControllerFindAllCreatorTypeEnum = typeof QuestionControllerFindAllCreatorTypeEnum[keyof typeof QuestionControllerFindAllCreatorTypeEnum];
export const QuestionControllerFindMyQuestionsOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type QuestionControllerFindMyQuestionsOrderEnum = typeof QuestionControllerFindMyQuestionsOrderEnum[keyof typeof QuestionControllerFindMyQuestionsOrderEnum];
