/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateSizeDto } from '../models';
// @ts-ignore
import type { UpdateSizeDto } from '../models';
/**
 * SizesApi - axios parameter creator
 */
export const SizesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary ახალი ზომის შექმნა (ADMIN)
         * @param {CreateSizeDto} createSizeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerCreate: async (createSizeDto: CreateSizeDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSizeDto' is not null or undefined
            assertParamExists('sizesControllerCreate', 'createSizeDto', createSizeDto)
            const localVarPath = `/sizes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSizeDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ზომების სია
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerFindAll: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/sizes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კონკრეტული ზომის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerFindOne: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sizesControllerFindOne', 'id', id)
            const localVarPath = `/sizes/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ზომის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerRemove: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sizesControllerRemove', 'id', id)
            const localVarPath = `/sizes/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ზომის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateSizeDto} updateSizeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerUpdate: async (id: string, updateSizeDto: UpdateSizeDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('sizesControllerUpdate', 'id', id)
            // verify required parameter 'updateSizeDto' is not null or undefined
            assertParamExists('sizesControllerUpdate', 'updateSizeDto', updateSizeDto)
            const localVarPath = `/sizes/{id}`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateSizeDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SizesApi - functional programming interface
 */
export const SizesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SizesApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary ახალი ზომის შექმნა (ADMIN)
         * @param {CreateSizeDto} createSizeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sizesControllerCreate(createSizeDto: CreateSizeDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sizesControllerCreate(createSizeDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SizesApi.sizesControllerCreate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ზომების სია
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sizesControllerFindAll(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sizesControllerFindAll(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SizesApi.sizesControllerFindAll']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კონკრეტული ზომის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sizesControllerFindOne(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sizesControllerFindOne(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SizesApi.sizesControllerFindOne']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ზომის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sizesControllerRemove(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sizesControllerRemove(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SizesApi.sizesControllerRemove']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ზომის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateSizeDto} updateSizeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sizesControllerUpdate(id: string, updateSizeDto: UpdateSizeDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sizesControllerUpdate(id, updateSizeDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SizesApi.sizesControllerUpdate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SizesApi - factory interface
 */
export const SizesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SizesApiFp(configuration)
    return {
        /**
         * 
         * @summary ახალი ზომის შექმნა (ADMIN)
         * @param {CreateSizeDto} createSizeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerCreate(createSizeDto: CreateSizeDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.sizesControllerCreate(createSizeDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ზომების სია
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerFindAll(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.sizesControllerFindAll(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კონკრეტული ზომის მიღება
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerFindOne(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.sizesControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ზომის წაშლა (ADMIN)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerRemove(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.sizesControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ზომის განახლება (ADMIN)
         * @param {string} id 
         * @param {UpdateSizeDto} updateSizeDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sizesControllerUpdate(id: string, updateSizeDto: UpdateSizeDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.sizesControllerUpdate(id, updateSizeDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SizesApi - object-oriented interface
 */
export class SizesApi extends BaseAPI {
    /**
     * 
     * @summary ახალი ზომის შექმნა (ADMIN)
     * @param {CreateSizeDto} createSizeDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sizesControllerCreate(createSizeDto: CreateSizeDto, options?: RawAxiosRequestConfig) {
        return SizesApiFp(this.configuration).sizesControllerCreate(createSizeDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ზომების სია
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sizesControllerFindAll(options?: RawAxiosRequestConfig) {
        return SizesApiFp(this.configuration).sizesControllerFindAll(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კონკრეტული ზომის მიღება
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sizesControllerFindOne(id: string, options?: RawAxiosRequestConfig) {
        return SizesApiFp(this.configuration).sizesControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ზომის წაშლა (ADMIN)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sizesControllerRemove(id: string, options?: RawAxiosRequestConfig) {
        return SizesApiFp(this.configuration).sizesControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ზომის განახლება (ADMIN)
     * @param {string} id 
     * @param {UpdateSizeDto} updateSizeDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public sizesControllerUpdate(id: string, updateSizeDto: UpdateSizeDto, options?: RawAxiosRequestConfig) {
        return SizesApiFp(this.configuration).sizesControllerUpdate(id, updateSizeDto, options).then((request) => request(this.axios, this.basePath));
    }
}

