/* tslint:disable */
/* eslint-disable */
/**
 * My First Nest API
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
/**
 * StatsApi - axios parameter creator
 */
export const StatsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary სტატისტიკა კატეგორიების მიხედვით
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetCategoriesStats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stats/categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ხმების გლობალური სტატისტიკა სქესისა და ასაკის მიხედვით
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetDemographics: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stats/demographics`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary გლობალური სტატისტიკა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetGlobalStats: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stats/global`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary პოპულარული კითხვები
         * @param {number} [limit] თითო კატეგორიაში დასაბრუნებელი ჩანაწერების რაოდენობა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetPopularQuestions: async (limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stats/popular-questions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კონკრეტული კითხვის სტატისტიკა სქესისა და ასაკის მიხედვით (მთლიანად და თითო პასუხზე)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetQuestionDemographics: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('statsControllerGetQuestionDemographics', 'id', id)
            const localVarPath = `/stats/questions/{id}/demographics`
                .replace('{id}', encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ხმების ტრენდები პერიოდის მიხედვით
         * @param {StatsControllerGetTrendsPeriodEnum} [period] პერიოდი, რომლისთვისაც აიგება ტრენდი
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetTrends: async (period?: StatsControllerGetTrendsPeriodEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stats/trends`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (period !== undefined) {
                localVarQueryParameter['period'] = period;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * StatsApi - functional programming interface
 */
export const StatsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = StatsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary სტატისტიკა კატეგორიების მიხედვით
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statsControllerGetCategoriesStats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.statsControllerGetCategoriesStats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.statsControllerGetCategoriesStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ხმების გლობალური სტატისტიკა სქესისა და ასაკის მიხედვით
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statsControllerGetDemographics(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.statsControllerGetDemographics(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.statsControllerGetDemographics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary გლობალური სტატისტიკა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statsControllerGetGlobalStats(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.statsControllerGetGlobalStats(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.statsControllerGetGlobalStats']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary პოპულარული კითხვები
         * @param {number} [limit] თითო კატეგორიაში დასაბრუნებელი ჩანაწერების რაოდენობა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statsControllerGetPopularQuestions(limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.statsControllerGetPopularQuestions(limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.statsControllerGetPopularQuestions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კონკრეტული კითხვის სტატისტიკა სქესისა და ასაკის მიხედვით (მთლიანად და თითო პასუხზე)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statsControllerGetQuestionDemographics(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.statsControllerGetQuestionDemographics(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.statsControllerGetQuestionDemographics']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ხმების ტრენდები პერიოდის მიხედვით
         * @param {StatsControllerGetTrendsPeriodEnum} [period] პერიოდი, რომლისთვისაც აიგება ტრენდი
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async statsControllerGetTrends(period?: StatsControllerGetTrendsPeriodEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.statsControllerGetTrends(period, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['StatsApi.statsControllerGetTrends']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * StatsApi - factory interface
 */
export const StatsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = StatsApiFp(configuration)
    return {
        /**
         * 
         * @summary სტატისტიკა კატეგორიების მიხედვით
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetCategoriesStats(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.statsControllerGetCategoriesStats(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ხმების გლობალური სტატისტიკა სქესისა და ასაკის მიხედვით
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetDemographics(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.statsControllerGetDemographics(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary გლობალური სტატისტიკა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetGlobalStats(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.statsControllerGetGlobalStats(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary პოპულარული კითხვები
         * @param {number} [limit] თითო კატეგორიაში დასაბრუნებელი ჩანაწერების რაოდენობა
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetPopularQuestions(limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.statsControllerGetPopularQuestions(limit, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კონკრეტული კითხვის სტატისტიკა სქესისა და ასაკის მიხედვით (მთლიანად და თითო პასუხზე)
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetQuestionDemographics(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.statsControllerGetQuestionDemographics(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ხმების ტრენდები პერიოდის მიხედვით
         * @param {StatsControllerGetTrendsPeriodEnum} [period] პერიოდი, რომლისთვისაც აიგება ტრენდი
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        statsControllerGetTrends(period?: StatsControllerGetTrendsPeriodEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.statsControllerGetTrends(period, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * StatsApi - object-oriented interface
 */
export class StatsApi extends BaseAPI {
    /**
     * 
     * @summary სტატისტიკა კატეგორიების მიხედვით
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public statsControllerGetCategoriesStats(options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).statsControllerGetCategoriesStats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ხმების გლობალური სტატისტიკა სქესისა და ასაკის მიხედვით
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public statsControllerGetDemographics(options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).statsControllerGetDemographics(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary გლობალური სტატისტიკა
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public statsControllerGetGlobalStats(options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).statsControllerGetGlobalStats(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary პოპულარული კითხვები
     * @param {number} [limit] თითო კატეგორიაში დასაბრუნებელი ჩანაწერების რაოდენობა
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public statsControllerGetPopularQuestions(limit?: number, options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).statsControllerGetPopularQuestions(limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კონკრეტული კითხვის სტატისტიკა სქესისა და ასაკის მიხედვით (მთლიანად და თითო პასუხზე)
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public statsControllerGetQuestionDemographics(id: string, options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).statsControllerGetQuestionDemographics(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ხმების ტრენდები პერიოდის მიხედვით
     * @param {StatsControllerGetTrendsPeriodEnum} [period] პერიოდი, რომლისთვისაც აიგება ტრენდი
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public statsControllerGetTrends(period?: StatsControllerGetTrendsPeriodEnum, options?: RawAxiosRequestConfig) {
        return StatsApiFp(this.configuration).statsControllerGetTrends(period, options).then((request) => request(this.axios, this.basePath));
    }
}

export const StatsControllerGetTrendsPeriodEnum = {
    Week: 'week',
    Month: 'month',
    Year: 'year',
} as const;
export type StatsControllerGetTrendsPeriodEnum = typeof StatsControllerGetTrendsPeriodEnum[keyof typeof StatsControllerGetTrendsPeriodEnum];
