/* tslint:disable */
/* eslint-disable */
/**
 * My First Nest API
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SubmitAnswerDto } from '../models';
/**
 * UserAnswerApi - axios parameter creator
 */
export const UserAnswerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary პროფილის \"აქტივობები\" - ხმა მიცემული კითხვები (pagination, ფილტრით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {UserAnswerControllerGetMyActivitiesOrderEnum} [order] დალაგების მიმართულება
         * @param {number} [category] კატეგორიის ID
         * @param {UserAnswerControllerGetMyActivitiesStatusEnum} [status] აქტიურობის სტატუსი (ვადაგასული კითხვები ავტომატურად ითვლება inactive-ად)
         * @param {UserAnswerControllerGetMyActivitiesApprovalStatusEnum} [approvalStatus] admin-ის განხილვის სტატუსი (მხ. user-ის დასმულ კითხვებს ეხება; admin-ის კითხვები ყოველთვის approved-ია)
         * @param {UserAnswerControllerGetMyActivitiesCreatorTypeEnum} [creatorType] ვინ დასვა კითხვა — admin თუ user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAnswerControllerGetMyActivities: async (page?: number, limit?: number, sortBy?: string, order?: UserAnswerControllerGetMyActivitiesOrderEnum, category?: number, status?: UserAnswerControllerGetMyActivitiesStatusEnum, approvalStatus?: UserAnswerControllerGetMyActivitiesApprovalStatusEnum, creatorType?: UserAnswerControllerGetMyActivitiesCreatorTypeEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user-answers/my-activities`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (sortBy !== undefined) {
                localVarQueryParameter['sortBy'] = sortBy;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }

            if (category !== undefined) {
                localVarQueryParameter['category'] = category;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (approvalStatus !== undefined) {
                localVarQueryParameter['approvalStatus'] = approvalStatus;
            }

            if (creatorType !== undefined) {
                localVarQueryParameter['creatorType'] = creatorType;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვების ID-ები, რომლებზეც მომხმარებელს აქვს ხმა მიცემული
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAnswerControllerGetMyVotedQuestions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user-answers/my-voted-questions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary კითხვის შედეგების ნახვა
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAnswerControllerGetResults: async (questionId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('userAnswerControllerGetResults', 'questionId', questionId)
            const localVarPath = `/user-answers/question/{questionId}/results`
                .replace('{questionId}', encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary ხმის მიცემა კითხვაზე (IP ტრექინგით)
         * @param {string} questionId 
         * @param {SubmitAnswerDto} submitAnswerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAnswerControllerSubmitAnswer: async (questionId: string, submitAnswerDto: SubmitAnswerDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'questionId' is not null or undefined
            assertParamExists('userAnswerControllerSubmitAnswer', 'questionId', questionId)
            // verify required parameter 'submitAnswerDto' is not null or undefined
            assertParamExists('userAnswerControllerSubmitAnswer', 'submitAnswerDto', submitAnswerDto)
            const localVarPath = `/user-answers/question/{questionId}`
                .replace('{questionId}', encodeURIComponent(String(questionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(submitAnswerDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserAnswerApi - functional programming interface
 */
export const UserAnswerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserAnswerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary პროფილის \"აქტივობები\" - ხმა მიცემული კითხვები (pagination, ფილტრით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {UserAnswerControllerGetMyActivitiesOrderEnum} [order] დალაგების მიმართულება
         * @param {number} [category] კატეგორიის ID
         * @param {UserAnswerControllerGetMyActivitiesStatusEnum} [status] აქტიურობის სტატუსი (ვადაგასული კითხვები ავტომატურად ითვლება inactive-ად)
         * @param {UserAnswerControllerGetMyActivitiesApprovalStatusEnum} [approvalStatus] admin-ის განხილვის სტატუსი (მხ. user-ის დასმულ კითხვებს ეხება; admin-ის კითხვები ყოველთვის approved-ია)
         * @param {UserAnswerControllerGetMyActivitiesCreatorTypeEnum} [creatorType] ვინ დასვა კითხვა — admin თუ user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAnswerControllerGetMyActivities(page?: number, limit?: number, sortBy?: string, order?: UserAnswerControllerGetMyActivitiesOrderEnum, category?: number, status?: UserAnswerControllerGetMyActivitiesStatusEnum, approvalStatus?: UserAnswerControllerGetMyActivitiesApprovalStatusEnum, creatorType?: UserAnswerControllerGetMyActivitiesCreatorTypeEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userAnswerControllerGetMyActivities(page, limit, sortBy, order, category, status, approvalStatus, creatorType, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserAnswerApi.userAnswerControllerGetMyActivities']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვების ID-ები, რომლებზეც მომხმარებელს აქვს ხმა მიცემული
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAnswerControllerGetMyVotedQuestions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userAnswerControllerGetMyVotedQuestions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserAnswerApi.userAnswerControllerGetMyVotedQuestions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary კითხვის შედეგების ნახვა
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAnswerControllerGetResults(questionId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userAnswerControllerGetResults(questionId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserAnswerApi.userAnswerControllerGetResults']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary ხმის მიცემა კითხვაზე (IP ტრექინგით)
         * @param {string} questionId 
         * @param {SubmitAnswerDto} submitAnswerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAnswerControllerSubmitAnswer(questionId: string, submitAnswerDto: SubmitAnswerDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.userAnswerControllerSubmitAnswer(questionId, submitAnswerDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserAnswerApi.userAnswerControllerSubmitAnswer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserAnswerApi - factory interface
 */
export const UserAnswerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserAnswerApiFp(configuration)
    return {
        /**
         * 
         * @summary პროფილის \"აქტივობები\" - ხმა მიცემული კითხვები (pagination, ფილტრით)
         * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
         * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
         * @param {string} [sortBy] დალაგების ველი
         * @param {UserAnswerControllerGetMyActivitiesOrderEnum} [order] დალაგების მიმართულება
         * @param {number} [category] კატეგორიის ID
         * @param {UserAnswerControllerGetMyActivitiesStatusEnum} [status] აქტიურობის სტატუსი (ვადაგასული კითხვები ავტომატურად ითვლება inactive-ად)
         * @param {UserAnswerControllerGetMyActivitiesApprovalStatusEnum} [approvalStatus] admin-ის განხილვის სტატუსი (მხ. user-ის დასმულ კითხვებს ეხება; admin-ის კითხვები ყოველთვის approved-ია)
         * @param {UserAnswerControllerGetMyActivitiesCreatorTypeEnum} [creatorType] ვინ დასვა კითხვა — admin თუ user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAnswerControllerGetMyActivities(page?: number, limit?: number, sortBy?: string, order?: UserAnswerControllerGetMyActivitiesOrderEnum, category?: number, status?: UserAnswerControllerGetMyActivitiesStatusEnum, approvalStatus?: UserAnswerControllerGetMyActivitiesApprovalStatusEnum, creatorType?: UserAnswerControllerGetMyActivitiesCreatorTypeEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.userAnswerControllerGetMyActivities(page, limit, sortBy, order, category, status, approvalStatus, creatorType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვების ID-ები, რომლებზეც მომხმარებელს აქვს ხმა მიცემული
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAnswerControllerGetMyVotedQuestions(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.userAnswerControllerGetMyVotedQuestions(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary კითხვის შედეგების ნახვა
         * @param {string} questionId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAnswerControllerGetResults(questionId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.userAnswerControllerGetResults(questionId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary ხმის მიცემა კითხვაზე (IP ტრექინგით)
         * @param {string} questionId 
         * @param {SubmitAnswerDto} submitAnswerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAnswerControllerSubmitAnswer(questionId: string, submitAnswerDto: SubmitAnswerDto, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.userAnswerControllerSubmitAnswer(questionId, submitAnswerDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserAnswerApi - object-oriented interface
 */
export class UserAnswerApi extends BaseAPI {
    /**
     * 
     * @summary პროფილის \"აქტივობები\" - ხმა მიცემული კითხვები (pagination, ფილტრით)
     * @param {number} [page] გვერდის ნომერი (იწყება 1-დან)
     * @param {number} [limit] ჩანაწერების რაოდენობა თითო გვერდზე
     * @param {string} [sortBy] დალაგების ველი
     * @param {UserAnswerControllerGetMyActivitiesOrderEnum} [order] დალაგების მიმართულება
     * @param {number} [category] კატეგორიის ID
     * @param {UserAnswerControllerGetMyActivitiesStatusEnum} [status] აქტიურობის სტატუსი (ვადაგასული კითხვები ავტომატურად ითვლება inactive-ად)
     * @param {UserAnswerControllerGetMyActivitiesApprovalStatusEnum} [approvalStatus] admin-ის განხილვის სტატუსი (მხ. user-ის დასმულ კითხვებს ეხება; admin-ის კითხვები ყოველთვის approved-ია)
     * @param {UserAnswerControllerGetMyActivitiesCreatorTypeEnum} [creatorType] ვინ დასვა კითხვა — admin თუ user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userAnswerControllerGetMyActivities(page?: number, limit?: number, sortBy?: string, order?: UserAnswerControllerGetMyActivitiesOrderEnum, category?: number, status?: UserAnswerControllerGetMyActivitiesStatusEnum, approvalStatus?: UserAnswerControllerGetMyActivitiesApprovalStatusEnum, creatorType?: UserAnswerControllerGetMyActivitiesCreatorTypeEnum, options?: RawAxiosRequestConfig) {
        return UserAnswerApiFp(this.configuration).userAnswerControllerGetMyActivities(page, limit, sortBy, order, category, status, approvalStatus, creatorType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვების ID-ები, რომლებზეც მომხმარებელს აქვს ხმა მიცემული
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userAnswerControllerGetMyVotedQuestions(options?: RawAxiosRequestConfig) {
        return UserAnswerApiFp(this.configuration).userAnswerControllerGetMyVotedQuestions(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary კითხვის შედეგების ნახვა
     * @param {string} questionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userAnswerControllerGetResults(questionId: string, options?: RawAxiosRequestConfig) {
        return UserAnswerApiFp(this.configuration).userAnswerControllerGetResults(questionId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary ხმის მიცემა კითხვაზე (IP ტრექინგით)
     * @param {string} questionId 
     * @param {SubmitAnswerDto} submitAnswerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public userAnswerControllerSubmitAnswer(questionId: string, submitAnswerDto: SubmitAnswerDto, options?: RawAxiosRequestConfig) {
        return UserAnswerApiFp(this.configuration).userAnswerControllerSubmitAnswer(questionId, submitAnswerDto, options).then((request) => request(this.axios, this.basePath));
    }
}

export const UserAnswerControllerGetMyActivitiesOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type UserAnswerControllerGetMyActivitiesOrderEnum = typeof UserAnswerControllerGetMyActivitiesOrderEnum[keyof typeof UserAnswerControllerGetMyActivitiesOrderEnum];
export const UserAnswerControllerGetMyActivitiesStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
} as const;
export type UserAnswerControllerGetMyActivitiesStatusEnum = typeof UserAnswerControllerGetMyActivitiesStatusEnum[keyof typeof UserAnswerControllerGetMyActivitiesStatusEnum];
export const UserAnswerControllerGetMyActivitiesApprovalStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected',
} as const;
export type UserAnswerControllerGetMyActivitiesApprovalStatusEnum = typeof UserAnswerControllerGetMyActivitiesApprovalStatusEnum[keyof typeof UserAnswerControllerGetMyActivitiesApprovalStatusEnum];
export const UserAnswerControllerGetMyActivitiesCreatorTypeEnum = {
    Admin: 'admin',
    User: 'user',
} as const;
export type UserAnswerControllerGetMyActivitiesCreatorTypeEnum = typeof UserAnswerControllerGetMyActivitiesCreatorTypeEnum[keyof typeof UserAnswerControllerGetMyActivitiesCreatorTypeEnum];
