/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AddCategoryAttributeDto {
    /**
     * მისაბმელი Attribute-ის ID
     */
    'attributeId': string;
    /**
     * დალაგების რიგი ამ კატეგორიის attribute set-ში
     */
    'sortOrder'?: number;
    /**
     * override — სავალდებულოა თუ არა ეს attribute ამ კონკრეტულ კატეგორიაზე (გამოტოვებისას attribute-ის საკუთარი isRequired გამოიყენება უცვლელად)
     */
    'isRequiredOverride'?: boolean;
}

