/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Product } from './product';

export interface Category {
    'id': string;
    'nameKa': string;
    'nameEn': string;
    'slug': string;
    'isActive': boolean;
    'sortOrder': number;
    'image'?: string;
    'seoTitle'?: string;
    'seoDescription'?: string;
    'seoKeywords'?: string;
    'parent'?: Category | null;
    'children'?: Array<Category>;
    'products'?: Array<Product>;
    'createdAt': string;
    'updatedAt': string;
}

