/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Category } from './category';
/**
*
*
* @export
* @interface CategoryResponseDto
*/
export interface CategoryResponseDto {
    /**
     * @type {number}
     * @memberof CategoryResponseDto
     * @example 200
     */
    statusCode: number;
    /**
     * @type {string}
     * @memberof CategoryResponseDto
     * @example კატეგორია წარმატებით შეიქმნა
     */
    message: string;
    /**
     * @type {Category}
     * @memberof CategoryResponseDto
     */
    data?: Category | null;
}
