/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface ChangePasswordResponseDto
*/
export interface ChangePasswordResponseDto {
    /**
     * @type {number}
     * @memberof ChangePasswordResponseDto
     * @example 200
     */
    statusCode: number;
    /**
     * @type {string}
     * @memberof ChangePasswordResponseDto
     * @example პაროლი წარმატებით შეიცვალა
     */
    message: string;
}
