/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface CreateTaskDto
*/
export interface CreateTaskDto {
    /**
     * @type {string}
     * @memberof CreateTaskDto
     */
    title: string;
    /**
     * @type {string}
     * @memberof CreateTaskDto
     */
    description?: string;
    /**
     * @type {boolean}
     * @memberof CreateTaskDto
     */
    isCompleted?: boolean;
}
