/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface CreateAnswerDto
*/
export interface CreateAnswerDto {
    /**
     * პასუხის ტექსტი
     *
     * @type {string}
     * @memberof CreateAnswerDto
     * @example თბილისი
     */
    text: string;
}
