/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NameTranslationsDto } from './name-translations-dto';

export interface CreateAttributeDto {
    /**
     * მრავალენოვანი სახელი — { ka: {name}, en?, ru? }, ka სავალდებულოა
     */
    'translations': NameTranslationsDto;
    /**
     * უნიკალური კოდი (frontend filter query-ებისთვის), მხოლოდ ლათინური ასოები/ციფრები/ტირე
     */
    'code': string;
    /**
     * მახასიათებლის ტიპი — განსაზღვრავს, product_attribute_value-ში რომელი value ველი გამოიყენება
     */
    'type': CreateAttributeDtoTypeEnum;
    /**
     * ერთეული (Ah, V, mm...) — number/range ტიპებისთვის
     */
    'unit'?: string;
    /**
     * გამოჩნდება თუ არა filter-ებში
     */
    'isFilterable'?: boolean;
    /**
     * სავალდებულოა თუ არა admin ფორმაში
     */
    'isRequired'?: boolean;
    /**
     * დალაგების რიგი
     */
    'sortOrder'?: number;
}

export const CreateAttributeDtoTypeEnum = {
    Select: 'select',
    MultiSelect: 'multi_select',
    Number: 'number',
    Text: 'text',
    Boolean: 'boolean',
    Range: 'range',
} as const;

export type CreateAttributeDtoTypeEnum = typeof CreateAttributeDtoTypeEnum[keyof typeof CreateAttributeDtoTypeEnum];


