/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateProductDto {
    /**
     * პროდუქტის სახელი
     */
    'name': string;
    /**
     * პროდუქტის აღწერა
     */
    'description'?: string;
    /**
     * ფასი
     */
    'price': number;
    /**
     * მარაგში რაოდენობა
     */
    'stock'?: number;
    /**
     * ფასდაკლება პროცენტებში (0-100)
     */
    'discountPercent'?: number;
    /**
     * სურათების URL-ების სია
     */
    'images'?: Array<string>;
    /**
     * YouTube ვიდეოს ლინკი (მიმოხილვა/ინსტრუქცია პროდუქტის გვერდზე)
     */
    'videoUrl'?: string;
    /**
     * წონა (კგ)
     */
    'weight'?: number;
    /**
     * სიგრძე (სმ)
     */
    'length'?: number;
    /**
     * სიგანე (სმ)
     */
    'width'?: number;
    /**
     * აქტიურია თუ არა პროდუქტი
     */
    'isActive'?: boolean;
    /**
     * კატეგორიის ID
     */
    'categoryId'?: string;
}

