/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface CreateUserDto
*/
export interface CreateUserDto {
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    role?: CreateUserDtoRoleEnum;
    /**
     * მომხმარებლის სქესი
     *
     * @type {string}
     * @memberof CreateUserDto
     */
    gender?: CreateUserDtoGenderEnum;
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    lastName: string;
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    password: string;
    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    email: string;
}
/**
 * @export
 * @enum {string}
 */
export declare enum CreateUserDtoRoleEnum {
    Admin = "admin",
    User = "user"
}
/**
 * @export
 * @enum {string}
 */
export declare enum CreateUserDtoGenderEnum {
    Male = "male",
    Female = "female"
}
