/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateUserDto {
    'role'?: CreateUserDtoRoleEnum;
    /**
     * მომხმარებლის სქესი
     */
    'gender'?: CreateUserDtoGenderEnum;
    /**
     * მომხმარებლის ასაკი
     */
    'age'?: number;
    /**
     * პირადი ნომერი — ზუსტად 11 ციფრი
     */
    'personalNumber'?: string;
    /**
     * მომხმარებლის ტელეფონის ნომერი
     */
    'phoneNumber'?: string;
    'firstName': string;
    'lastName': string;
    'password': string;
    'email': string;
}

export const CreateUserDtoRoleEnum = {
    Admin: 'admin',
    User: 'user',
} as const;

export type CreateUserDtoRoleEnum = typeof CreateUserDtoRoleEnum[keyof typeof CreateUserDtoRoleEnum];
export const CreateUserDtoGenderEnum = {
    Male: 'male',
    Female: 'female',
} as const;

export type CreateUserDtoGenderEnum = typeof CreateUserDtoGenderEnum[keyof typeof CreateUserDtoGenderEnum];


