/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateOrderDto {
    /**
     * მიწოდების ხერხი — საკურიერო ან ფილიალიდან გატანა
     */
    'deliveryMethod'?: CreateOrderDtoDeliveryMethodEnum;
    /**
     * მიწოდების მისამართი (deliveryMethod=courier-სთვის სავალდებულო)
     */
    'shippingAddress'?: string;
    /**
     * არჩეული ფილიალის ID (deliveryMethod=pickup-სთვის სავალდებულო)
     */
    'branchId'?: number;
}

export const CreateOrderDtoDeliveryMethodEnum = {
    Courier: 'courier',
    Pickup: 'pickup',
} as const;

export type CreateOrderDtoDeliveryMethodEnum = typeof CreateOrderDtoDeliveryMethodEnum[keyof typeof CreateOrderDtoDeliveryMethodEnum];


