/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BranchWorkingHoursDto } from './branch-working-hours-dto';

export interface CreateBranchDto {
    /**
     * მფლობელი კომპანიის ID (წინასწარ /companies-ზე შექმნილი)
     */
    'companyId': string;
    'title': string;
    'address': string;
    'phoneNumber': string;
    'email'?: string;
    /**
     * რუკის განედი (latitude)
     */
    'latitude': number;
    /**
     * რუკის გრძედი (longitude)
     */
    'longitude': number;
    'workingHours': BranchWorkingHoursDto;
    'isActive'?: boolean;
    'sortOrder'?: number;
}

