/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CustomerLoyaltyDto {
    /**
     * პერიოდში 2 ან მეტი გადახდილი შეკვეთის მქონე მომხმარებელთა რაოდენობა
     */
    'repeatCustomers': number;
    /**
     * პერიოდში ზუსტად 1 გადახდილი შეკვეთის მქონე მომხმარებელთა რაოდენობა
     */
    'oneTimeCustomers': number;
    /**
     * repeatCustomers-ის წილი პროცენტებში ყველა შემძენ მომხმარებელს შორის — null, თუ პერიოდში საერთოდ არავის უყიდია
     */
    'repeatRatePercent': number | null;
}

