/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DashboardOverviewDto {
    /**
     * დღევანდელი შემოსავალი (გადახდილი სტატუსების შეკვეთები)
     */
    'todayRevenue': number;
    /**
     * მიმდინარე თვის შემოსავალი (გადახდილი სტატუსების შეკვეთები)
     */
    'monthRevenue': number;
    /**
     * აქტიური შეკვეთების რაოდენობა (PENDING + PROCESSING)
     */
    'activeOrdersCount': number;
    /**
     * დღეს დარეგისტრირებული ახალი მომხმარებლების რაოდენობა
     */
    'newUsersToday': number;
    /**
     * დაბალი მარაგის მქონე აქტიური პროდუქტების რაოდენობა
     */
    'lowStockCount': number;
}

