/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Question } from './question';
import { User } from './user';
/**
*
*
* @export
* @interface Favorite
*/
export interface Favorite {
    /**
     * @type {number}
     * @memberof Favorite
     */
    id: number;
    /**
     * @type {User}
     * @memberof Favorite
     */
    user: User;
    /**
     * @type {Question}
     * @memberof Favorite
     */
    question: Question;
    /**
     * @type {Date}
     * @memberof Favorite
     */
    createdAt: Date;
}
