/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { HeroSlideTranslationDto } from './hero-slide-translation-dto';

export interface HeroSlideTranslationsDto {
    'ka': HeroSlideTranslationDto;
    'en'?: HeroSlideTranslationDto;
    'ru'?: HeroSlideTranslationDto;
}

