/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface HeroSlideTranslationDto {
    /**
     * მთავარი სათაურის ზემოთ პატარა ტექსტი (eyebrow)
     */
    'eyebrow'?: string;
    /**
     * სლაიდის სათაური
     */
    'title': string;
    /**
     * სლაიდის აღწერილობა
     */
    'description'?: string;
    /**
     * ღილაკის ტექსტი
     */
    'buttonText'?: string;
}

