/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface NotificationActionDto {
    /**
     * ღილაკზე გამოსახული ტექსტი
     */
    'label': string;
    /**
     * close — მხოლოდ მოდალს ხურავს; link — გადადის url-ზე
     */
    'type': NotificationActionDtoTypeEnum;
    /**
     * type=link-ის შემთხვევაში სავალდებულო, http(s) URL
     */
    'url'?: string;
}

export const NotificationActionDtoTypeEnum = {
    Close: 'close',
    Link: 'link',
} as const;

export type NotificationActionDtoTypeEnum = typeof NotificationActionDtoTypeEnum[keyof typeof NotificationActionDtoTypeEnum];


