/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { PaginationMetaDto } from './pagination-meta-dto';
/**
*
*
* @export
* @interface PaginatedResponseDto
*/
export interface PaginatedResponseDto {
    /**
     * მონაცემთა მასივი
     *
     * @type {Array<Array>}
     * @memberof PaginatedResponseDto
     */
    data: Array<Array>;
    /**
     * პაგინაციის მეტაინფორმაცია
     *
     * @type {PaginationMetaDto}
     * @memberof PaginatedResponseDto
     */
    meta: PaginationMetaDto;
}
