/* tslint:disable */
/* eslint-disable */
/**
 * My First Nest API
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMetaDto } from './pagination-meta-dto';

export interface PaginatedResponseDto {
    /**
     * მონაცემთა მასივი
     */
    'data': Array<object>;
    /**
     * პაგინაციის მეტაინფორმაცია
     */
    'meta': PaginationMetaDto;
}

