/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Category } from './category';
// May contain unused imports in some cases
// @ts-ignore
import type { Company } from './company';

export interface Product {
    'id': number;
    'translations': object;
    'price': string;
    'stock': number;
    'discountPercent'?: number;
    'images'?: Array<string>;
    'videoUrl'?: string;
    'weight'?: string;
    'length'?: string;
    'width'?: string;
    'isActive': boolean;
    'category'?: Category;
    'company'?: Company;
    'createdAt': string;
    'updatedAt': string;
}

