/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProductBranchItemDto {
    /**
     * Branch-ის ID (წინასწარ /branches-ზე შექმნილი)
     */
    'branchId': number;
    /**
     * ამ ფილიალის მარაგი ამ პროდუქტისთვის (ცალი)
     */
    'stock': number;
}

