/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProductStatDto {
    /**
     * პროდუქტის ID — null, თუ პროდუქტი შემდგომში წაშლილია (snapshot productName მაინც ჩანს)
     */
    'productId': number | null;
    'productName': string;
    /**
     * გაყიდული ერთეულების ჯამი
     */
    'quantitySold': number;
    /**
     * ჯამური შემოსავალი ამ პროდუქტიდან
     */
    'revenue': number;
}

