/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ProductAttributeValueItemDto {
    /**
     * Attribute-ის ID, რომლისთვისაც მნიშვნელობა ინახება
     */
    'attributeId': string;
    /**
     * არჩეული option (select ტიპისთვის)
     */
    'attributeOptionId'?: string;
    /**
     * არჩეული option-ები (multi_select ტიპისთვის)
     */
    'attributeOptionIds'?: Array<string>;
    /**
     * ტექსტური მნიშვნელობა (text ტიპისთვის)
     */
    'valueText'?: string;
    /**
     * რიცხვითი მნიშვნელობა (number/range ტიპისთვის)
     */
    'valueNumber'?: number;
    /**
     * ლოგიკური მნიშვნელობა (boolean ტიპისთვის)
     */
    'valueBoolean'?: boolean;
}

