/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Answer } from './answer';
/**
*
*
* @export
* @interface Question
*/
export interface Question {
    /**
     * @type {number}
     * @memberof Question
     */
    id: number;
    /**
     * @type {string}
     * @memberof Question
     */
    text: string;
    /**
     * @type {string}
     * @memberof Question
     */
    type: QuestionTypeEnum;
    /**
     * @type {Array<Answer>}
     * @memberof Question
     */
    answers: Array<Answer>;
    /**
     * @type {Date}
     * @memberof Question
     */
    createdAt: Date;
}
/**
 * @export
 * @enum {string}
 */
export declare enum QuestionTypeEnum {
    Single = "single",
    Multiple = "multiple"
}
