/* tslint:disable */
/* eslint-disable */
/**
 * My First Nest API
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Answer } from './answer';
// May contain unused imports in some cases
// @ts-ignore
import type { Category } from './category';
// May contain unused imports in some cases
// @ts-ignore
import type { User } from './user';

export interface Question {
    'id': number;
    'text': string;
    'type': QuestionTypeEnum;
    'answers': Array<Answer>;
    'categories'?: Array<Category>;
    'isActive': boolean;
    'endDate'?: string | null;
    'creatorType': QuestionCreatorTypeEnum;
    'createdBy'?: User;
    'createdById'?: number;
    'creatorIp'?: string;
    'approvalStatus': QuestionApprovalStatusEnum;
    'rejectionReason'?: string | null;
    'reviewedBy'?: User;
    'reviewedById'?: number;
    'reviewedAt'?: string | null;
    'createdAt': string;
    'isPinned': boolean;
    'pinnedAt'?: string | null;
}

export const QuestionTypeEnum = {
    Single: 'single',
    Multiple: 'multiple',
} as const;

export type QuestionTypeEnum = typeof QuestionTypeEnum[keyof typeof QuestionTypeEnum];
export const QuestionCreatorTypeEnum = {
    Admin: 'admin',
    User: 'user',
} as const;

export type QuestionCreatorTypeEnum = typeof QuestionCreatorTypeEnum[keyof typeof QuestionCreatorTypeEnum];
export const QuestionApprovalStatusEnum = {
    Pending: 'pending',
    Approved: 'approved',
    Rejected: 'rejected',
} as const;

export type QuestionApprovalStatusEnum = typeof QuestionApprovalStatusEnum[keyof typeof QuestionApprovalStatusEnum];


