/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Answer } from './answer';
import { Category } from './category';
import { User } from './user';
/**
*
*
* @export
* @interface Question
*/
export interface Question {
    /**
     * @type {number}
     * @memberof Question
     */
    id: number;
    /**
     * @type {string}
     * @memberof Question
     */
    text: string;
    /**
     * @type {string}
     * @memberof Question
     */
    type: QuestionTypeEnum;
    /**
     * @type {Array<Answer>}
     * @memberof Question
     */
    answers: Array<Answer>;
    /**
     * @type {Category}
     * @memberof Question
     */
    category?: Category;
    /**
     * @type {number}
     * @memberof Question
     */
    categoryId?: number;
    /**
     * @type {boolean}
     * @memberof Question
     */
    isActive: boolean;
    /**
     * @type {Date}
     * @memberof Question
     */
    endDate?: Date | null;
    /**
     * @type {string}
     * @memberof Question
     */
    creatorType: QuestionCreatorTypeEnum;
    /**
     * @type {User}
     * @memberof Question
     */
    createdBy?: User;
    /**
     * @type {number}
     * @memberof Question
     */
    createdById?: number;
    /**
     * @type {string}
     * @memberof Question
     */
    creatorIp?: string;
    /**
     * @type {string}
     * @memberof Question
     */
    approvalStatus: QuestionApprovalStatusEnum;
    /**
     * @type {string}
     * @memberof Question
     */
    rejectionReason?: string | null;
    /**
     * @type {User}
     * @memberof Question
     */
    reviewedBy?: User;
    /**
     * @type {number}
     * @memberof Question
     */
    reviewedById?: number;
    /**
     * @type {Date}
     * @memberof Question
     */
    reviewedAt?: Date | null;
    /**
     * @type {Date}
     * @memberof Question
     */
    createdAt: Date;
}
/**
 * @export
 * @enum {string}
 */
export declare enum QuestionTypeEnum {
    Single = "single",
    Multiple = "multiple"
}
/**
 * @export
 * @enum {string}
 */
export declare enum QuestionCreatorTypeEnum {
    Admin = "admin",
    User = "user"
}
/**
 * @export
 * @enum {string}
 */
export declare enum QuestionApprovalStatusEnum {
    Pending = "pending",
    Approved = "approved",
    Rejected = "rejected"
}
