/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TokenDataDto } from './token-data-dto';
/**
*
*
* @export
* @interface RegisterResponseDto
*/
export interface RegisterResponseDto {
    /**
     * @type {number}
     * @memberof RegisterResponseDto
     * @example 201
     */
    statusCode: number;
    /**
     * @type {string}
     * @memberof RegisterResponseDto
     * @example მომხმარებელი წარმატებით დარეგისტრირდა
     */
    message: string;
    /**
     * @type {TokenDataDto}
     * @memberof RegisterResponseDto
     */
    data: TokenDataDto;
}
