/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface RegisterDto
*/
export interface RegisterDto {
    /**
     * მომხმარებლის სქესი
     *
     * @type {string}
     * @memberof RegisterDto
     */
    gender?: RegisterDtoGenderEnum;
    /**
     * @type {string}
     * @memberof RegisterDto
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof RegisterDto
     */
    lastName: string;
    /**
     * @type {string}
     * @memberof RegisterDto
     */
    email: string;
    /**
     * @type {string}
     * @memberof RegisterDto
     */
    password: string;
}
/**
 * @export
 * @enum {string}
 */
export declare enum RegisterDtoGenderEnum {
    Male = "male",
    Female = "female"
}
