/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface RegisterDto {
    /**
     * მომხმარებლის სქესი
     */
    'gender'?: RegisterDtoGenderEnum;
    /**
     * მომხმარებლის ასაკი
     */
    'age'?: number;
    /**
     * პირადი ნომერი — ზუსტად 11 ციფრი
     */
    'personalNumber'?: string;
    /**
     * POST /otp/send-ის პასუხიდან მიღებული requestId — თუ SMS ვერიფიკაცია ჩართულია, სავალდებულოა otpCode-თან ერთად
     */
    'otpRequestId'?: string;
    /**
     * მომხმარებლის მობილურზე მიღებული OTP კოდი
     */
    'otpCode'?: string;
    'firstName': string;
    'lastName': string;
    'email': string;
    'password': string;
    'phoneNumber': string;
}

export const RegisterDtoGenderEnum = {
    Male: 'male',
    Female: 'female',
} as const;

export type RegisterDtoGenderEnum = typeof RegisterDtoGenderEnum[keyof typeof RegisterDtoGenderEnum];


