/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface StatusTransitionAvgItemDto {
    'fromStatus': StatusTransitionAvgItemDtoFromStatusEnum;
    'toStatus': StatusTransitionAvgItemDtoToStatusEnum;
    /**
     * საშუალო ხანგრძლივობა წამებში ამ გადასვლისთვის
     */
    'avgSeconds': number;
    /**
     * ადამიანისთვის წაკითხვადი ფორმატი avgSeconds-ის
     */
    'avgHumanReadable': string;
    /**
     * რამდენჯერ მოხდა ეს კონკრეტული გადასვლა პერიოდში
     */
    'transitionCount': number;
}

export const StatusTransitionAvgItemDtoFromStatusEnum = {
    Pending: 'pending',
    Paid: 'paid',
    Processing: 'processing',
    Shipped: 'shipped',
    Delivered: 'delivered',
    Cancelled: 'cancelled',
    Expired: 'expired',
} as const;

export type StatusTransitionAvgItemDtoFromStatusEnum = typeof StatusTransitionAvgItemDtoFromStatusEnum[keyof typeof StatusTransitionAvgItemDtoFromStatusEnum];
export const StatusTransitionAvgItemDtoToStatusEnum = {
    Pending: 'pending',
    Paid: 'paid',
    Processing: 'processing',
    Shipped: 'shipped',
    Delivered: 'delivered',
    Cancelled: 'cancelled',
    Expired: 'expired',
} as const;

export type StatusTransitionAvgItemDtoToStatusEnum = typeof StatusTransitionAvgItemDtoToStatusEnum[keyof typeof StatusTransitionAvgItemDtoToStatusEnum];


