/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserDataDto } from './user-data-dto';
/**
*
*
* @export
* @interface TokenDataDto
*/
export interface TokenDataDto {
    /**
     * @type {string}
     * @memberof TokenDataDto
     * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
     */
    accessToken: string;
    /**
     * @type {UserDataDto}
     * @memberof TokenDataDto
     */
    user: UserDataDto;
}
