/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateUserDto {
    'role'?: UpdateUserDtoRoleEnum;
    /**
     * მომხმარებლის სქესი
     */
    'gender'?: UpdateUserDtoGenderEnum;
    /**
     * მომხმარებლის ასაკი
     */
    'age'?: number;
    'firstName'?: string;
    'lastName'?: string;
    'password'?: string;
    'email'?: string;
}

export const UpdateUserDtoRoleEnum = {
    Admin: 'admin',
    User: 'user',
} as const;

export type UpdateUserDtoRoleEnum = typeof UpdateUserDtoRoleEnum[keyof typeof UpdateUserDtoRoleEnum];
export const UpdateUserDtoGenderEnum = {
    Male: 'male',
    Female: 'female',
} as const;

export type UpdateUserDtoGenderEnum = typeof UpdateUserDtoGenderEnum[keyof typeof UpdateUserDtoGenderEnum];


