/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CreateAnswerDto } from './create-answer-dto';
/**
*
*
* @export
* @interface UpdateQuestionDto
*/
export interface UpdateQuestionDto {
    /**
     * კატეგორიის ID (optional)
     *
     * @type {number}
     * @memberof UpdateQuestionDto
     * @example 1
     */
    categoryId?: number;
    /**
     * @type {string}
     * @memberof UpdateQuestionDto
     */
    text?: string;
    /**
     * @type {string}
     * @memberof UpdateQuestionDto
     */
    type?: UpdateQuestionDtoTypeEnum;
    /**
     * @type {Array<CreateAnswerDto>}
     * @memberof UpdateQuestionDto
     */
    answers?: Array<CreateAnswerDto>;
}
/**
 * @export
 * @enum {string}
 */
export declare enum UpdateQuestionDtoTypeEnum {
    Single = "single",
    Multiple = "multiple"
}
