/* tslint:disable */
/* eslint-disable */
/**
 * My First Nest API
 * The API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateAnswerDto } from './create-answer-dto';

export interface UpdateQuestionDto {
    /**
     * კატეგორიების ID-ები (optional, ერთ კითხვას შეიძლება რამდენიმე კატეგორია ჰქონდეს)
     */
    'categoryIds'?: Array<number>;
    /**
     * აქტიურია თუ არა კითხვა (მხოლოდ admin-ის შექმნილ კითხვას ეხება — user-ის კითხვისთვის ეს ველი იგნორირდება)
     */
    'isActive'?: boolean;
    /**
     * დასრულების თარიღი (ISO ფორმატი). ვადის გასვლის შემდეგ კითხვა ავტომატურად გადავა დეაქტივირებულ სიაში. მხოლოდ admin-ის შექმნილ კითხვას ეხება — user-ის მიერ გამოგზავნილი ეს ველი იგნორირდება (user-ის კითხვისთვის დამთავრების თარიღეს ადგენს admin approve-ის დროს)
     */
    'endDate'?: string;
    'text'?: string;
    'type'?: UpdateQuestionDtoTypeEnum;
    'answers'?: Array<CreateAnswerDto>;
}

export const UpdateQuestionDtoTypeEnum = {
    Single: 'single',
    Multiple: 'multiple',
} as const;

export type UpdateQuestionDtoTypeEnum = typeof UpdateQuestionDtoTypeEnum[keyof typeof UpdateQuestionDtoTypeEnum];


