/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface UpdateUserDto
*/
export interface UpdateUserDto {
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    role?: UpdateUserDtoRoleEnum;
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    firstName?: string;
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    lastName?: string;
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    password?: string;
    /**
     * @type {string}
     * @memberof UpdateUserDto
     */
    email?: string;
}
/**
 * @export
 * @enum {string}
 */
export declare enum UpdateUserDtoRoleEnum {
    Admin = "admin",
    User = "user"
}
