/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface UpdateAttributeDto {
    /**
     * მახასიათებლის სახელი ქართულად
     */
    'nameKa'?: string;
    /**
     * მახასიათებლის სახელი ინგლისურად
     */
    'nameEn'?: string;
    /**
     * უნიკალური კოდი (frontend filter query-ებისთვის), მხოლოდ ლათინური ასოები/ციფრები/ტირე
     */
    'code'?: string;
    /**
     * მახასიათებლის ტიპი — განსაზღვრავს, product_attribute_value-ში რომელი value ველი გამოიყენება
     */
    'type'?: UpdateAttributeDtoTypeEnum;
    /**
     * ერთეული (Ah, V, mm...) — number/range ტიპებისთვის
     */
    'unit'?: string;
    /**
     * გამოჩნდება თუ არა filter-ებში
     */
    'isFilterable'?: boolean;
    /**
     * სავალდებულოა თუ არა admin ფორმაში
     */
    'isRequired'?: boolean;
    /**
     * დალაგების რიგი
     */
    'sortOrder'?: number;
}

export const UpdateAttributeDtoTypeEnum = {
    Select: 'select',
    MultiSelect: 'multi_select',
    Number: 'number',
    Text: 'text',
    Boolean: 'boolean',
    Range: 'range',
} as const;

export type UpdateAttributeDtoTypeEnum = typeof UpdateAttributeDtoTypeEnum[keyof typeof UpdateAttributeDtoTypeEnum];


