/* tslint:disable */
/* eslint-disable */
/**
 * Online Shop API
 * REST API for the online shop backend
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ValueTranslationsDto } from './value-translations-dto';

export interface UpdateAttributeOptionDto {
    /**
     * მრავალენოვანი მნიშვნელობა — { ka: {value}, en?, ru? }, ka სავალდებულოა
     */
    'translations'?: ValueTranslationsDto;
    /**
     * უნიკალური კოდი (attribute-ის ფარგლებში), მხოლოდ ლათინური ასოები/ციფრები/ტირე
     */
    'code'?: string;
    /**
     * დალაგების რიგი
     */
    'sortOrder'?: number;
}

