/**
 * My First Nest API
 * The API description
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
*
*
* @export
* @interface UserDataDto
*/
export interface UserDataDto {
    /**
     * @type {number}
     * @memberof UserDataDto
     * @example 1
     */
    id: number;
    /**
     * @type {string}
     * @memberof UserDataDto
     * @example test@test.com
     */
    email: string;
    /**
     * @type {string}
     * @memberof UserDataDto
     * @example გიორგი
     */
    firstName: string;
    /**
     * @type {string}
     * @memberof UserDataDto
     * @example ბერიძე
     */
    lastName: string;
}
